import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE INDEX "_blog_v_blocks_pink_puffy_parent_id_idx" ON "_blog_v_blocks_pink_puffy" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_pink_puffy_path_idx" ON "_blog_v_blocks_pink_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_pink_puffy_locales_locale_parent_id_unique" ON "_blog_v_blocks_pink_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_beige_puffy_items_order_idx" ON "_blog_v_blocks_beige_puffy_items" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_beige_puffy_items_parent_id_idx" ON "_blog_v_blocks_beige_puffy_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_beige_puffy_items_locales_locale_parent_id_un" ON "_blog_v_blocks_beige_puffy_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_beige_puffy_order_idx" ON "_blog_v_blocks_beige_puffy" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_beige_puffy_parent_id_idx" ON "_blog_v_blocks_beige_puffy" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_beige_puffy_path_idx" ON "_blog_v_blocks_beige_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_beige_puffy_locales_locale_parent_id_unique" ON "_blog_v_blocks_beige_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_funding_map_items_subitems_order_idx" ON "_blog_v_blocks_funding_map_items_subitems" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_funding_map_items_subitems_parent_id_idx" ON "_blog_v_blocks_funding_map_items_subitems" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_funding_map_items_subitems_locales_locale_par" ON "_blog_v_blocks_funding_map_items_subitems_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_funding_map_items_order_idx" ON "_blog_v_blocks_funding_map_items" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_funding_map_items_parent_id_idx" ON "_blog_v_blocks_funding_map_items" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_funding_map_order_idx" ON "_blog_v_blocks_funding_map" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_funding_map_parent_id_idx" ON "_blog_v_blocks_funding_map" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_funding_map_path_idx" ON "_blog_v_blocks_funding_map" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_funding_map_locales_locale_parent_id_unique" ON "_blog_v_blocks_funding_map_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_resource_feat_card_order_idx" ON "_blog_v_blocks_resource_feat_card" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_resource_feat_card_parent_id_idx" ON "_blog_v_blocks_resource_feat_card" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_resource_feat_card_path_idx" ON "_blog_v_blocks_resource_feat_card" USING btree ("_path");
  CREATE INDEX "_blog_v_blocks_resource_feat_card_filter_by_doc_type_idx" ON "_blog_v_blocks_resource_feat_card" USING btree ("filter_by_doc_type_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_resource_feat_card_locales_locale_parent_id_u" ON "_blog_v_blocks_resource_feat_card_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_resource_gallery_order_idx" ON "_blog_v_blocks_resource_gallery" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_resource_gallery_parent_id_idx" ON "_blog_v_blocks_resource_gallery" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_resource_gallery_path_idx" ON "_blog_v_blocks_resource_gallery" USING btree ("_path");
  CREATE INDEX "_blog_v_blocks_resource_gallery_filter_by_doc_type_idx" ON "_blog_v_blocks_resource_gallery" USING btree ("filter_by_doc_type_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_resource_gallery_locales_locale_parent_id_uni" ON "_blog_v_blocks_resource_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_pillar_card_cards_order_idx" ON "_blog_v_blocks_pillar_card_cards" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_pillar_card_cards_parent_id_idx" ON "_blog_v_blocks_pillar_card_cards" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_pillar_card_cards_mascot_idx" ON "_blog_v_blocks_pillar_card_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_pillar_card_cards_locales_locale_parent_id_un" ON "_blog_v_blocks_pillar_card_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_pillar_card_order_idx" ON "_blog_v_blocks_pillar_card" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_pillar_card_parent_id_idx" ON "_blog_v_blocks_pillar_card" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_pillar_card_path_idx" ON "_blog_v_blocks_pillar_card" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_pillar_card_locales_locale_parent_id_unique" ON "_blog_v_blocks_pillar_card_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_testimonial_deck_cards_order_idx" ON "_blog_v_blocks_testimonial_deck_cards" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_testimonial_deck_cards_parent_id_idx" ON "_blog_v_blocks_testimonial_deck_cards" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_testimonial_deck_cards_locales_locale_parent_" ON "_blog_v_blocks_testimonial_deck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_testimonial_deck_order_idx" ON "_blog_v_blocks_testimonial_deck" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_testimonial_deck_parent_id_idx" ON "_blog_v_blocks_testimonial_deck" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_testimonial_deck_path_idx" ON "_blog_v_blocks_testimonial_deck" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_testimonial_deck_locales_locale_parent_id_uni" ON "_blog_v_blocks_testimonial_deck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_min_card_gallery_cards_order_idx" ON "_blog_v_blocks_min_card_gallery_cards" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_min_card_gallery_cards_parent_id_idx" ON "_blog_v_blocks_min_card_gallery_cards" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_min_card_gallery_cards_mascot_idx" ON "_blog_v_blocks_min_card_gallery_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_min_card_gallery_cards_locales_locale_parent_" ON "_blog_v_blocks_min_card_gallery_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_min_card_gallery_order_idx" ON "_blog_v_blocks_min_card_gallery" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_min_card_gallery_parent_id_idx" ON "_blog_v_blocks_min_card_gallery" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_min_card_gallery_path_idx" ON "_blog_v_blocks_min_card_gallery" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_min_card_gallery_locales_locale_parent_id_uni" ON "_blog_v_blocks_min_card_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_id_card_gallery_cards_order_idx" ON "_blog_v_blocks_id_card_gallery_cards" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_id_card_gallery_cards_parent_id_idx" ON "_blog_v_blocks_id_card_gallery_cards" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_id_card_gallery_cards_mascot_idx" ON "_blog_v_blocks_id_card_gallery_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_id_card_gallery_cards_locales_locale_parent_i" ON "_blog_v_blocks_id_card_gallery_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_id_card_gallery_order_idx" ON "_blog_v_blocks_id_card_gallery" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_id_card_gallery_parent_id_idx" ON "_blog_v_blocks_id_card_gallery" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_id_card_gallery_path_idx" ON "_blog_v_blocks_id_card_gallery" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_id_card_gallery_locales_locale_parent_id_uniq" ON "_blog_v_blocks_id_card_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_two_column_block_order_idx" ON "_blog_v_blocks_two_column_block" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_two_column_block_parent_id_idx" ON "_blog_v_blocks_two_column_block" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_two_column_block_path_idx" ON "_blog_v_blocks_two_column_block" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_two_column_block_locales_locale_parent_id_uni" ON "_blog_v_blocks_two_column_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_three_column_table_block_rows_order_idx" ON "_blog_v_blocks_three_column_table_block_rows" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_three_column_table_block_rows_parent_id_idx" ON "_blog_v_blocks_three_column_table_block_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_blog_v_blocks_three_column_table_block_rows_locales_locale_" ON "_blog_v_blocks_three_column_table_block_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_blocks_three_column_table_block_order_idx" ON "_blog_v_blocks_three_column_table_block" USING btree ("_order");
  CREATE INDEX "_blog_v_blocks_three_column_table_block_parent_id_idx" ON "_blog_v_blocks_three_column_table_block" USING btree ("_parent_id");
  CREATE INDEX "_blog_v_blocks_three_column_table_block_path_idx" ON "_blog_v_blocks_three_column_table_block" USING btree ("_path");
  CREATE UNIQUE INDEX "_blog_v_blocks_three_column_table_block_locales_locale_paren" ON "_blog_v_blocks_three_column_table_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_parent_idx" ON "_blog_v" USING btree ("parent_id");
  CREATE INDEX "_blog_v_version_version_title_idx" ON "_blog_v" USING btree ("version_title");
  CREATE INDEX "_blog_v_version_version_image_idx" ON "_blog_v" USING btree ("version_image_id");
  CREATE INDEX "_blog_v_version_version_created_by_idx" ON "_blog_v" USING btree ("version_created_by_id");
  CREATE INDEX "_blog_v_version_version_updated_by_idx" ON "_blog_v" USING btree ("version_updated_by_id");
  CREATE INDEX "_blog_v_version_version_slug_idx" ON "_blog_v" USING btree ("version_slug");
  CREATE INDEX "_blog_v_version_meta_version_meta_image_idx" ON "_blog_v" USING btree ("version_meta_image_id");
  CREATE INDEX "_blog_v_version_version_folder_idx" ON "_blog_v" USING btree ("version_folder_id");
  CREATE INDEX "_blog_v_version_version_updated_at_idx" ON "_blog_v" USING btree ("version_updated_at");
  CREATE INDEX "_blog_v_version_version_created_at_idx" ON "_blog_v" USING btree ("version_created_at");
  CREATE INDEX "_blog_v_version_version_deleted_at_idx" ON "_blog_v" USING btree ("version_deleted_at");
  CREATE INDEX "_blog_v_version_version__status_idx" ON "_blog_v" USING btree ("version__status");
  CREATE INDEX "_blog_v_created_at_idx" ON "_blog_v" USING btree ("created_at");
  CREATE INDEX "_blog_v_updated_at_idx" ON "_blog_v" USING btree ("updated_at");
  CREATE INDEX "_blog_v_snapshot_idx" ON "_blog_v" USING btree ("snapshot");
  CREATE INDEX "_blog_v_published_locale_idx" ON "_blog_v" USING btree ("published_locale");
  CREATE INDEX "_blog_v_latest_idx" ON "_blog_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_blog_v_locales_locale_parent_id_unique" ON "_blog_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_rels_order_idx" ON "_blog_v_rels" USING btree ("order");
  CREATE INDEX "_blog_v_rels_parent_idx" ON "_blog_v_rels" USING btree ("parent_id");
  CREATE INDEX "_blog_v_rels_path_idx" ON "_blog_v_rels" USING btree ("path");
  CREATE INDEX "_blog_v_rels_doctypes_id_idx" ON "_blog_v_rels" USING btree ("doctypes_id");
  CREATE INDEX "_blog_v_rels_grants_id_idx" ON "_blog_v_rels" USING btree ("grants_id");
  CREATE INDEX "_blog_v_rels_pages_id_idx" ON "_blog_v_rels" USING btree ("pages_id");
  CREATE INDEX "_blog_v_rels_blog_id_idx" ON "_blog_v_rels" USING btree ("blog_id");
  CREATE INDEX "_blog_v_rels_reports_id_idx" ON "_blog_v_rels" USING btree ("reports_id");
  CREATE INDEX "_blog_v_rels_mmedia_id_idx" ON "_blog_v_rels" USING btree ("mmedia_id");
  CREATE INDEX "_blog_v_rels_documents_id_idx" ON "_blog_v_rels" USING btree ("documents_id");
  CREATE INDEX "_blog_v_rels_etests_id_idx" ON "_blog_v_rels" USING btree ("etests_id");
  CREATE INDEX "_blog_v_rels_grantcards_id_idx" ON "_blog_v_rels" USING btree ("grantcards_id");
  CREATE INDEX "reports_hero_buttons_order_idx" ON "reports_hero_buttons" USING btree ("_order");
  CREATE INDEX "reports_hero_buttons_parent_id_idx" ON "reports_hero_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_hero_buttons_locales_locale_parent_id_unique" ON "reports_hero_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_rich_content_block_order_idx" ON "reports_blocks_rich_content_block" USING btree ("_order");
  CREATE INDEX "reports_blocks_rich_content_block_parent_id_idx" ON "reports_blocks_rich_content_block" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_rich_content_block_path_idx" ON "reports_blocks_rich_content_block" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_rich_content_block_locales_locale_parent_id_u" ON "reports_blocks_rich_content_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_secondarycta_cta_button_order_idx" ON "reports_blocks_secondarycta_cta_button" USING btree ("_order");
  CREATE INDEX "reports_blocks_secondarycta_cta_button_parent_id_idx" ON "reports_blocks_secondarycta_cta_button" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_secondarycta_cta_button_locales_locale_parent" ON "reports_blocks_secondarycta_cta_button_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_secondarycta_order_idx" ON "reports_blocks_secondarycta" USING btree ("_order");
  CREATE INDEX "reports_blocks_secondarycta_parent_id_idx" ON "reports_blocks_secondarycta" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_secondarycta_path_idx" ON "reports_blocks_secondarycta" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_secondarycta_locales_locale_parent_id_unique" ON "reports_blocks_secondarycta_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_mcol_info_block_multicols_order_idx" ON "reports_blocks_mcol_info_block_multicols" USING btree ("_order");
  CREATE INDEX "reports_blocks_mcol_info_block_multicols_parent_id_idx" ON "reports_blocks_mcol_info_block_multicols" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_mcol_info_block_multicols_locales_locale_pare" ON "reports_blocks_mcol_info_block_multicols_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_mcol_info_block_order_idx" ON "reports_blocks_mcol_info_block" USING btree ("_order");
  CREATE INDEX "reports_blocks_mcol_info_block_parent_id_idx" ON "reports_blocks_mcol_info_block" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_mcol_info_block_path_idx" ON "reports_blocks_mcol_info_block" USING btree ("_path");
  CREATE INDEX "reports_blocks_grant_card_grid_block_order_idx" ON "reports_blocks_grant_card_grid_block" USING btree ("_order");
  CREATE INDEX "reports_blocks_grant_card_grid_block_parent_id_idx" ON "reports_blocks_grant_card_grid_block" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_grant_card_grid_block_path_idx" ON "reports_blocks_grant_card_grid_block" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_grant_card_grid_block_locales_locale_parent_i" ON "reports_blocks_grant_card_grid_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_mstep_process_steps_details_order_idx" ON "reports_blocks_mstep_process_steps_details" USING btree ("_order");
  CREATE INDEX "reports_blocks_mstep_process_steps_details_parent_id_idx" ON "reports_blocks_mstep_process_steps_details" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_mstep_process_steps_details_locales_locale_pa" ON "reports_blocks_mstep_process_steps_details_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_mstep_process_steps_order_idx" ON "reports_blocks_mstep_process_steps" USING btree ("_order");
  CREATE INDEX "reports_blocks_mstep_process_steps_parent_id_idx" ON "reports_blocks_mstep_process_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_mstep_process_steps_locales_locale_parent_id_" ON "reports_blocks_mstep_process_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_mstep_process_order_idx" ON "reports_blocks_mstep_process" USING btree ("_order");
  CREATE INDEX "reports_blocks_mstep_process_parent_id_idx" ON "reports_blocks_mstep_process" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_mstep_process_path_idx" ON "reports_blocks_mstep_process" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_mstep_process_locales_locale_parent_id_unique" ON "reports_blocks_mstep_process_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_comparison_blk_lft_grp_lft_points_order_idx" ON "reports_blocks_comparison_blk_lft_grp_lft_points" USING btree ("_order");
  CREATE INDEX "reports_blocks_comparison_blk_lft_grp_lft_points_parent_id_idx" ON "reports_blocks_comparison_blk_lft_grp_lft_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_comparison_blk_lft_grp_lft_points_locales_loc" ON "reports_blocks_comparison_blk_lft_grp_lft_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_comparison_blk_rt_grp_rt_points_order_idx" ON "reports_blocks_comparison_blk_rt_grp_rt_points" USING btree ("_order");
  CREATE INDEX "reports_blocks_comparison_blk_rt_grp_rt_points_parent_id_idx" ON "reports_blocks_comparison_blk_rt_grp_rt_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_comparison_blk_rt_grp_rt_points_locales_local" ON "reports_blocks_comparison_blk_rt_grp_rt_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_comparison_blk_buttons_order_idx" ON "reports_blocks_comparison_blk_buttons" USING btree ("_order");
  CREATE INDEX "reports_blocks_comparison_blk_buttons_parent_id_idx" ON "reports_blocks_comparison_blk_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_comparison_blk_buttons_locales_locale_parent_" ON "reports_blocks_comparison_blk_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_comparison_blk_order_idx" ON "reports_blocks_comparison_blk" USING btree ("_order");
  CREATE INDEX "reports_blocks_comparison_blk_parent_id_idx" ON "reports_blocks_comparison_blk" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_comparison_blk_path_idx" ON "reports_blocks_comparison_blk" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_comparison_blk_locales_locale_parent_id_uniqu" ON "reports_blocks_comparison_blk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_ylw_deck_cards_links_order_idx" ON "reports_blocks_ylw_deck_cards_links" USING btree ("_order");
  CREATE INDEX "reports_blocks_ylw_deck_cards_links_parent_id_idx" ON "reports_blocks_ylw_deck_cards_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_ylw_deck_cards_links_locales_locale_parent_id" ON "reports_blocks_ylw_deck_cards_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_ylw_deck_cards_order_idx" ON "reports_blocks_ylw_deck_cards" USING btree ("_order");
  CREATE INDEX "reports_blocks_ylw_deck_cards_parent_id_idx" ON "reports_blocks_ylw_deck_cards" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_ylw_deck_cards_mascot_idx" ON "reports_blocks_ylw_deck_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "reports_blocks_ylw_deck_cards_locales_locale_parent_id_uniqu" ON "reports_blocks_ylw_deck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_ylw_deck_order_idx" ON "reports_blocks_ylw_deck" USING btree ("_order");
  CREATE INDEX "reports_blocks_ylw_deck_parent_id_idx" ON "reports_blocks_ylw_deck" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_ylw_deck_path_idx" ON "reports_blocks_ylw_deck" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_ylw_deck_locales_locale_parent_id_unique" ON "reports_blocks_ylw_deck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_tags_order_idx" ON "reports_blocks_feat_crd_tags" USING btree ("_order");
  CREATE INDEX "reports_blocks_feat_crd_tags_parent_id_idx" ON "reports_blocks_feat_crd_tags" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_feat_crd_tags_locales_locale_parent_id_unique" ON "reports_blocks_feat_crd_tags_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_order_idx" ON "reports_blocks_feat_crd" USING btree ("_order");
  CREATE INDEX "reports_blocks_feat_crd_parent_id_idx" ON "reports_blocks_feat_crd" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_path_idx" ON "reports_blocks_feat_crd" USING btree ("_path");
  CREATE INDEX "reports_blocks_feat_crd_image_idx" ON "reports_blocks_feat_crd" USING btree ("image_id");
  CREATE UNIQUE INDEX "reports_blocks_feat_crd_locales_locale_parent_id_unique" ON "reports_blocks_feat_crd_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_acc_feat_crds_order_idx" ON "reports_blocks_feat_crd_acc_feat_crds" USING btree ("_order");
  CREATE INDEX "reports_blocks_feat_crd_acc_feat_crds_parent_id_idx" ON "reports_blocks_feat_crd_acc_feat_crds" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_acc_feat_crds_mascot_idx" ON "reports_blocks_feat_crd_acc_feat_crds" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "reports_blocks_feat_crd_acc_feat_crds_locales_locale_parent_" ON "reports_blocks_feat_crd_acc_feat_crds_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_acc_order_idx" ON "reports_blocks_feat_crd_acc" USING btree ("_order");
  CREATE INDEX "reports_blocks_feat_crd_acc_parent_id_idx" ON "reports_blocks_feat_crd_acc" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_feat_crd_acc_path_idx" ON "reports_blocks_feat_crd_acc" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_feat_crd_acc_locales_locale_parent_id_unique" ON "reports_blocks_feat_crd_acc_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_list_crd_dck_cards_tags_order_idx" ON "reports_blocks_list_crd_dck_cards_tags" USING btree ("_order");
  CREATE INDEX "reports_blocks_list_crd_dck_cards_tags_parent_id_idx" ON "reports_blocks_list_crd_dck_cards_tags" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_list_crd_dck_cards_tags_locales_locale_parent" ON "reports_blocks_list_crd_dck_cards_tags_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_list_crd_dck_cards_order_idx" ON "reports_blocks_list_crd_dck_cards" USING btree ("_order");
  CREATE INDEX "reports_blocks_list_crd_dck_cards_parent_id_idx" ON "reports_blocks_list_crd_dck_cards" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_list_crd_dck_cards_image_idx" ON "reports_blocks_list_crd_dck_cards" USING btree ("image_id");
  CREATE UNIQUE INDEX "reports_blocks_list_crd_dck_cards_locales_locale_parent_id_u" ON "reports_blocks_list_crd_dck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_list_crd_dck_buttons_order_idx" ON "reports_blocks_list_crd_dck_buttons" USING btree ("_order");
  CREATE INDEX "reports_blocks_list_crd_dck_buttons_parent_id_idx" ON "reports_blocks_list_crd_dck_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_list_crd_dck_buttons_locales_locale_parent_id" ON "reports_blocks_list_crd_dck_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_list_crd_dck_order_idx" ON "reports_blocks_list_crd_dck" USING btree ("_order");
  CREATE INDEX "reports_blocks_list_crd_dck_parent_id_idx" ON "reports_blocks_list_crd_dck" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_list_crd_dck_path_idx" ON "reports_blocks_list_crd_dck" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_list_crd_dck_locales_locale_parent_id_unique" ON "reports_blocks_list_crd_dck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_faq_blk_faqs_order_idx" ON "reports_blocks_faq_blk_faqs" USING btree ("_order");
  CREATE INDEX "reports_blocks_faq_blk_faqs_parent_id_idx" ON "reports_blocks_faq_blk_faqs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_faq_blk_faqs_locales_locale_parent_id_unique" ON "reports_blocks_faq_blk_faqs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_faq_blk_order_idx" ON "reports_blocks_faq_blk" USING btree ("_order");
  CREATE INDEX "reports_blocks_faq_blk_parent_id_idx" ON "reports_blocks_faq_blk" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_faq_blk_path_idx" ON "reports_blocks_faq_blk" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_faq_blk_locales_locale_parent_id_unique" ON "reports_blocks_faq_blk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_pink_puffy_top_row_order_idx" ON "reports_blocks_pink_puffy_top_row" USING btree ("_order");
  CREATE INDEX "reports_blocks_pink_puffy_top_row_parent_id_idx" ON "reports_blocks_pink_puffy_top_row" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_pink_puffy_top_row_locales_locale_parent_id_u" ON "reports_blocks_pink_puffy_top_row_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_pink_puffy_bot_row_order_idx" ON "reports_blocks_pink_puffy_bot_row" USING btree ("_order");
  CREATE INDEX "reports_blocks_pink_puffy_bot_row_parent_id_idx" ON "reports_blocks_pink_puffy_bot_row" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_pink_puffy_bot_row_locales_locale_parent_id_u" ON "reports_blocks_pink_puffy_bot_row_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_pink_puffy_links_order_idx" ON "reports_blocks_pink_puffy_links" USING btree ("_order");
  CREATE INDEX "reports_blocks_pink_puffy_links_parent_id_idx" ON "reports_blocks_pink_puffy_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_pink_puffy_links_locales_locale_parent_id_uni" ON "reports_blocks_pink_puffy_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_pink_puffy_order_idx" ON "reports_blocks_pink_puffy" USING btree ("_order");
  CREATE INDEX "reports_blocks_pink_puffy_parent_id_idx" ON "reports_blocks_pink_puffy" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_pink_puffy_path_idx" ON "reports_blocks_pink_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_pink_puffy_locales_locale_parent_id_unique" ON "reports_blocks_pink_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_beige_puffy_items_order_idx" ON "reports_blocks_beige_puffy_items" USING btree ("_order");
  CREATE INDEX "reports_blocks_beige_puffy_items_parent_id_idx" ON "reports_blocks_beige_puffy_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_beige_puffy_items_locales_locale_parent_id_un" ON "reports_blocks_beige_puffy_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_beige_puffy_order_idx" ON "reports_blocks_beige_puffy" USING btree ("_order");
  CREATE INDEX "reports_blocks_beige_puffy_parent_id_idx" ON "reports_blocks_beige_puffy" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_beige_puffy_path_idx" ON "reports_blocks_beige_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_beige_puffy_locales_locale_parent_id_unique" ON "reports_blocks_beige_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_funding_map_items_subitems_order_idx" ON "reports_blocks_funding_map_items_subitems" USING btree ("_order");
  CREATE INDEX "reports_blocks_funding_map_items_subitems_parent_id_idx" ON "reports_blocks_funding_map_items_subitems" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_funding_map_items_subitems_locales_locale_par" ON "reports_blocks_funding_map_items_subitems_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_funding_map_items_order_idx" ON "reports_blocks_funding_map_items" USING btree ("_order");
  CREATE INDEX "reports_blocks_funding_map_items_parent_id_idx" ON "reports_blocks_funding_map_items" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_funding_map_order_idx" ON "reports_blocks_funding_map" USING btree ("_order");
  CREATE INDEX "reports_blocks_funding_map_parent_id_idx" ON "reports_blocks_funding_map" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_funding_map_path_idx" ON "reports_blocks_funding_map" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_funding_map_locales_locale_parent_id_unique" ON "reports_blocks_funding_map_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_resource_feat_card_order_idx" ON "reports_blocks_resource_feat_card" USING btree ("_order");
  CREATE INDEX "reports_blocks_resource_feat_card_parent_id_idx" ON "reports_blocks_resource_feat_card" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_resource_feat_card_path_idx" ON "reports_blocks_resource_feat_card" USING btree ("_path");
  CREATE INDEX "reports_blocks_resource_feat_card_filter_by_doc_type_idx" ON "reports_blocks_resource_feat_card" USING btree ("filter_by_doc_type_id");
  CREATE UNIQUE INDEX "reports_blocks_resource_feat_card_locales_locale_parent_id_u" ON "reports_blocks_resource_feat_card_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_resource_gallery_order_idx" ON "reports_blocks_resource_gallery" USING btree ("_order");
  CREATE INDEX "reports_blocks_resource_gallery_parent_id_idx" ON "reports_blocks_resource_gallery" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_resource_gallery_path_idx" ON "reports_blocks_resource_gallery" USING btree ("_path");
  CREATE INDEX "reports_blocks_resource_gallery_filter_by_doc_type_idx" ON "reports_blocks_resource_gallery" USING btree ("filter_by_doc_type_id");
  CREATE UNIQUE INDEX "reports_blocks_resource_gallery_locales_locale_parent_id_uni" ON "reports_blocks_resource_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_pillar_card_cards_order_idx" ON "reports_blocks_pillar_card_cards" USING btree ("_order");
  CREATE INDEX "reports_blocks_pillar_card_cards_parent_id_idx" ON "reports_blocks_pillar_card_cards" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_pillar_card_cards_mascot_idx" ON "reports_blocks_pillar_card_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "reports_blocks_pillar_card_cards_locales_locale_parent_id_un" ON "reports_blocks_pillar_card_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_pillar_card_order_idx" ON "reports_blocks_pillar_card" USING btree ("_order");
  CREATE INDEX "reports_blocks_pillar_card_parent_id_idx" ON "reports_blocks_pillar_card" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_pillar_card_path_idx" ON "reports_blocks_pillar_card" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_pillar_card_locales_locale_parent_id_unique" ON "reports_blocks_pillar_card_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_testimonial_deck_cards_order_idx" ON "reports_blocks_testimonial_deck_cards" USING btree ("_order");
  CREATE INDEX "reports_blocks_testimonial_deck_cards_parent_id_idx" ON "reports_blocks_testimonial_deck_cards" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_testimonial_deck_cards_locales_locale_parent_" ON "reports_blocks_testimonial_deck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_testimonial_deck_order_idx" ON "reports_blocks_testimonial_deck" USING btree ("_order");
  CREATE INDEX "reports_blocks_testimonial_deck_parent_id_idx" ON "reports_blocks_testimonial_deck" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_testimonial_deck_path_idx" ON "reports_blocks_testimonial_deck" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_testimonial_deck_locales_locale_parent_id_uni" ON "reports_blocks_testimonial_deck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_min_card_gallery_cards_order_idx" ON "reports_blocks_min_card_gallery_cards" USING btree ("_order");
  CREATE INDEX "reports_blocks_min_card_gallery_cards_parent_id_idx" ON "reports_blocks_min_card_gallery_cards" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_min_card_gallery_cards_mascot_idx" ON "reports_blocks_min_card_gallery_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "reports_blocks_min_card_gallery_cards_locales_locale_parent_" ON "reports_blocks_min_card_gallery_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_min_card_gallery_order_idx" ON "reports_blocks_min_card_gallery" USING btree ("_order");
  CREATE INDEX "reports_blocks_min_card_gallery_parent_id_idx" ON "reports_blocks_min_card_gallery" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_min_card_gallery_path_idx" ON "reports_blocks_min_card_gallery" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_min_card_gallery_locales_locale_parent_id_uni" ON "reports_blocks_min_card_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_id_card_gallery_cards_order_idx" ON "reports_blocks_id_card_gallery_cards" USING btree ("_order");
  CREATE INDEX "reports_blocks_id_card_gallery_cards_parent_id_idx" ON "reports_blocks_id_card_gallery_cards" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_id_card_gallery_cards_mascot_idx" ON "reports_blocks_id_card_gallery_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "reports_blocks_id_card_gallery_cards_locales_locale_parent_i" ON "reports_blocks_id_card_gallery_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_id_card_gallery_order_idx" ON "reports_blocks_id_card_gallery" USING btree ("_order");
  CREATE INDEX "reports_blocks_id_card_gallery_parent_id_idx" ON "reports_blocks_id_card_gallery" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_id_card_gallery_path_idx" ON "reports_blocks_id_card_gallery" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_id_card_gallery_locales_locale_parent_id_uniq" ON "reports_blocks_id_card_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_two_column_block_order_idx" ON "reports_blocks_two_column_block" USING btree ("_order");
  CREATE INDEX "reports_blocks_two_column_block_parent_id_idx" ON "reports_blocks_two_column_block" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_two_column_block_path_idx" ON "reports_blocks_two_column_block" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_two_column_block_locales_locale_parent_id_uni" ON "reports_blocks_two_column_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_three_column_table_block_rows_order_idx" ON "reports_blocks_three_column_table_block_rows" USING btree ("_order");
  CREATE INDEX "reports_blocks_three_column_table_block_rows_parent_id_idx" ON "reports_blocks_three_column_table_block_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "reports_blocks_three_column_table_block_rows_locales_locale_" ON "reports_blocks_three_column_table_block_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_blocks_three_column_table_block_order_idx" ON "reports_blocks_three_column_table_block" USING btree ("_order");
  CREATE INDEX "reports_blocks_three_column_table_block_parent_id_idx" ON "reports_blocks_three_column_table_block" USING btree ("_parent_id");
  CREATE INDEX "reports_blocks_three_column_table_block_path_idx" ON "reports_blocks_three_column_table_block" USING btree ("_path");
  CREATE UNIQUE INDEX "reports_blocks_three_column_table_block_locales_locale_paren" ON "reports_blocks_three_column_table_block_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "reports_title_idx" ON "reports" USING btree ("title");
  CREATE INDEX "reports_image_idx" ON "reports" USING btree ("image_id");
  CREATE INDEX "reports_created_by_idx" ON "reports" USING btree ("created_by_id");
  CREATE INDEX "reports_updated_by_idx" ON "reports" USING btree ("updated_by_id");
  CREATE INDEX "reports_slug_idx" ON "reports" USING btree ("slug");
  CREATE INDEX "reports_meta_meta_image_idx" ON "reports" USING btree ("meta_image_id");
  CREATE INDEX "reports_folder_idx" ON "reports" USING btree ("folder_id");
  CREATE INDEX "reports_updated_at_idx" ON "reports" USING btree ("updated_at");
  CREATE INDEX "reports_created_at_idx" ON "reports" USING btree ("created_at");
  CREATE INDEX "reports_deleted_at_idx" ON "reports" USING btree ("deleted_at");
  CREATE INDEX "reports__status_idx" ON "reports" USING btree ("_status");
  CREATE UNIQUE INDEX "reports_locales_locale_parent_id_unique" ON "reports_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "reports_rels_order_idx" ON "reports_rels" USING btree ("order");
  CREATE INDEX "reports_rels_parent_idx" ON "reports_rels" USING btree ("parent_id");
  CREATE INDEX "reports_rels_path_idx" ON "reports_rels" USING btree ("path");
  CREATE INDEX "reports_rels_doctypes_id_idx" ON "reports_rels" USING btree ("doctypes_id");
  CREATE INDEX "reports_rels_grants_id_idx" ON "reports_rels" USING btree ("grants_id");
  CREATE INDEX "reports_rels_pages_id_idx" ON "reports_rels" USING btree ("pages_id");
  CREATE INDEX "reports_rels_blog_id_idx" ON "reports_rels" USING btree ("blog_id");
  CREATE INDEX "reports_rels_reports_id_idx" ON "reports_rels" USING btree ("reports_id");
  CREATE INDEX "reports_rels_mmedia_id_idx" ON "reports_rels" USING btree ("mmedia_id");
  CREATE INDEX "reports_rels_documents_id_idx" ON "reports_rels" USING btree ("documents_id");
  CREATE INDEX "reports_rels_etests_id_idx" ON "reports_rels" USING btree ("etests_id");
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // no-op
}
