import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "payload_migrations" (
    "id" serial PRIMARY KEY NOT NULL,
    "name" varchar,
    "batch" numeric,
    "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
    "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  CREATE INDEX IF NOT EXISTS "payload_migrations_updated_at_idx" ON "payload_migrations" USING btree ("updated_at");
  CREATE INDEX IF NOT EXISTS "payload_migrations_created_at_idx" ON "payload_migrations" USING btree ("created_at");
  `)

  await db.execute(sql`
  CREATE TYPE "public"."_locales" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_grants_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum_grants_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum_grants_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum_grants_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_grants_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum_grants_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum_grants_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum_grants_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grants_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_grants_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_grants_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum_grants_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_grants_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_grants_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_grants_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_grants_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum_grants_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum_grants_bg_type" AS ENUM('wavy_top', 'wavy_full', 'center_blob');
  CREATE TYPE "public"."enum_grants_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__grants_v_version_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum__grants_v_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum__grants_v_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum__grants_v_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__grants_v_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum__grants_v_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum__grants_v_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum__grants_v_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grants_v_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__grants_v_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__grants_v_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum__grants_v_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__grants_v_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__grants_v_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__grants_v_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__grants_v_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum__grants_v_version_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum__grants_v_version_bg_type" AS ENUM('wavy_top', 'wavy_full', 'center_blob');
  CREATE TYPE "public"."enum__grants_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__grants_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_grantcards_card_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_grantcards_badge_type" AS ENUM('info', 'imp', 'inactive');
  CREATE TYPE "public"."enum_grantcards_active_period" AS ENUM('open_all_year', 'specific_period', 'closed');
  CREATE TYPE "public"."enum_grantcards_card_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire', 'trans');
  CREATE TYPE "public"."enum_grantcards_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__grantcards_v_version_card_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__grantcards_v_version_badge_type" AS ENUM('info', 'imp', 'inactive');
  CREATE TYPE "public"."enum__grantcards_v_version_active_period" AS ENUM('open_all_year', 'specific_period', 'closed');
  CREATE TYPE "public"."enum__grantcards_v_version_card_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire', 'trans');
  CREATE TYPE "public"."enum__grantcards_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__grantcards_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_etests_is_e_card_is_e_link_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_etests_not_e_card_not_e_link_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_etests_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__etests_v_version_is_e_card_is_e_link_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__etests_v_version_not_e_card_not_e_link_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__etests_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__etests_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_pages_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum_pages_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum_pages_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum_pages_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum_pages_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum_pages_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_pages_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_pages_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_pages_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum_pages_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum_pages_bg_type" AS ENUM('wavy_top', 'wavy_full', 'center_blob');
  CREATE TYPE "public"."enum_pages_hero_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire', 'trans');
  CREATE TYPE "public"."enum_pages_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__pages_v_version_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum__pages_v_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum__pages_v_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum__pages_v_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum__pages_v_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__pages_v_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__pages_v_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__pages_v_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum__pages_v_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum__pages_v_version_bg_type" AS ENUM('wavy_top', 'wavy_full', 'center_blob');
  CREATE TYPE "public"."enum__pages_v_version_hero_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire', 'trans');
  CREATE TYPE "public"."enum__pages_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__pages_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_blog_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum_blog_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum_blog_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum_blog_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_blog_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum_blog_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum_blog_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum_blog_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_blog_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_blog_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_blog_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum_blog_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_blog_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_blog_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_blog_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_blog_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum_blog_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum_blog_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__blog_v_version_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum__blog_v_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum__blog_v_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum__blog_v_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__blog_v_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum__blog_v_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum__blog_v_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum__blog_v_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__blog_v_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__blog_v_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__blog_v_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum__blog_v_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__blog_v_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__blog_v_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__blog_v_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__blog_v_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum__blog_v_version_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum__blog_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__blog_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_reports_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum_reports_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum_reports_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum_reports_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_reports_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum_reports_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum_reports_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum_reports_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_reports_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_reports_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_reports_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum_reports_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_reports_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_reports_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_reports_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_reports_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum_reports_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum_reports_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__reports_v_version_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum__reports_v_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum__reports_v_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum__reports_v_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__reports_v_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum__reports_v_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum__reports_v_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum__reports_v_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__reports_v_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__reports_v_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__reports_v_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum__reports_v_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__reports_v_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__reports_v_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__reports_v_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__reports_v_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum__reports_v_version_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum__reports_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__reports_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_mmedia_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum_mmedia_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum_mmedia_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum_mmedia_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_mmedia_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum_mmedia_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum_mmedia_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum_mmedia_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum_mmedia_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_mmedia_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum_mmedia_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum_mmedia_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_mmedia_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_mmedia_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_mmedia_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_mmedia_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum_mmedia_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum_mmedia_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__mmedia_v_version_hero_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_secondarycta_cta_button_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_secondarycta_ui_type" AS ENUM('lrg_txt_cta', 'md_txt_cta', 'min_cta', 'puffy_beige_cta');
  CREATE TYPE "public"."enum__mmedia_v_blocks_mcol_info_block_multicols_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_mstep_process_steps_icon" AS ENUM('FileText', 'Clock', 'ShieldCheck', 'Vote', 'ScrollText', 'Banknote', 'Rocket', 'FileCheck');
  CREATE TYPE "public"."enum__mmedia_v_blocks_comparison_blk_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_ylw_deck_cards_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_ylw_deck_cards_mascot_pos" AS ENUM('top_left', 'center');
  CREATE TYPE "public"."enum__mmedia_v_blocks_ylw_deck_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__mmedia_v_blocks_feat_crd_title_alignment" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum__mmedia_v_blocks_feat_crd_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_feat_crd_acc_feat_crds_crd_colour" AS ENUM('forest', 'turmeric', 'sky', 'rose', 'lavender', 'fire');
  CREATE TYPE "public"."enum__mmedia_v_blocks_list_crd_dck_cards_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_list_crd_dck_buttons_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_list_crd_dck_data_source" AS ENUM('manual', 'resources');
  CREATE TYPE "public"."enum__mmedia_v_blocks_faq_blk_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_pink_puffy_links_link_type" AS ENUM('reference', 'custom', 'email', 'document', 'etest');
  CREATE TYPE "public"."enum__mmedia_v_blocks_pink_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__mmedia_v_blocks_beige_puffy_align" AS ENUM('center', 'left');
  CREATE TYPE "public"."enum__mmedia_v_blocks_funding_map_items_region_name" AS ENUM('uaf-asia-pacific', 'afghan', 'aus', 'bangla', 'cambodia', 'china', 'india', 'indonesia', 'korea', 'laos', 'malaysia', 'mongolia', 'myanmar', 'nepal', 'pak', 'papua', 'philippines', 'srilanka', 'thailand', 'vietnam');
  CREATE TYPE "public"."enum__mmedia_v_blocks_resource_feat_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__mmedia_v_blocks_resource_gallery_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__mmedia_v_blocks_pillar_card_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__mmedia_v_blocks_min_card_gallery_header_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__mmedia_v_blocks_three_column_table_block_column_widths" AS ENUM('f-t-t', 't-f-t', 't-t-f', 'vt-t-f');
  CREATE TYPE "public"."enum__mmedia_v_version_page_type" AS ENUM('landing', 'individual');
  CREATE TYPE "public"."enum__mmedia_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__mmedia_v_published_locale" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur', 'lpl1', 'lpl2', 'lpl3', 'lpl4', 'lpl5', 'lpl6', 'lpl7', 'lpl8', 'lpl9', 'lpl10');
  CREATE TYPE "public"."enum_users_assigned_languages" AS ENUM('en', 'ar', 'bi', 'bn-IN', 'br', 'ch', 'prs-Arab', 'km', 'hi', 'ms', 'ne', 'ps-Arab', 'pcm', 'si', 'tl', 'ta', 'th', 'vi', 'ur');
  CREATE TYPE "public"."enum_users_role" AS ENUM('admin', 'editor', 'writer', 'translator');
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // no-op
}
