import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE INDEX "_grants_v_blocks_pillar_card_cards_mascot_idx" ON "_grants_v_blocks_pillar_card_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "_grants_v_blocks_pillar_card_cards_locales_locale_parent_id_" ON "_grants_v_blocks_pillar_card_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_pillar_card_order_idx" ON "_grants_v_blocks_pillar_card" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_pillar_card_parent_id_idx" ON "_grants_v_blocks_pillar_card" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_pillar_card_path_idx" ON "_grants_v_blocks_pillar_card" USING btree ("_path");
  CREATE UNIQUE INDEX "_grants_v_blocks_pillar_card_locales_locale_parent_id_unique" ON "_grants_v_blocks_pillar_card_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_testimonial_deck_cards_order_idx" ON "_grants_v_blocks_testimonial_deck_cards" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_testimonial_deck_cards_parent_id_idx" ON "_grants_v_blocks_testimonial_deck_cards" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_grants_v_blocks_testimonial_deck_cards_locales_locale_paren" ON "_grants_v_blocks_testimonial_deck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_testimonial_deck_order_idx" ON "_grants_v_blocks_testimonial_deck" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_testimonial_deck_parent_id_idx" ON "_grants_v_blocks_testimonial_deck" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_testimonial_deck_path_idx" ON "_grants_v_blocks_testimonial_deck" USING btree ("_path");
  CREATE UNIQUE INDEX "_grants_v_blocks_testimonial_deck_locales_locale_parent_id_u" ON "_grants_v_blocks_testimonial_deck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_min_card_gallery_cards_order_idx" ON "_grants_v_blocks_min_card_gallery_cards" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_min_card_gallery_cards_parent_id_idx" ON "_grants_v_blocks_min_card_gallery_cards" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_min_card_gallery_cards_mascot_idx" ON "_grants_v_blocks_min_card_gallery_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "_grants_v_blocks_min_card_gallery_cards_locales_locale_paren" ON "_grants_v_blocks_min_card_gallery_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_min_card_gallery_order_idx" ON "_grants_v_blocks_min_card_gallery" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_min_card_gallery_parent_id_idx" ON "_grants_v_blocks_min_card_gallery" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_min_card_gallery_path_idx" ON "_grants_v_blocks_min_card_gallery" USING btree ("_path");
  CREATE UNIQUE INDEX "_grants_v_blocks_min_card_gallery_locales_locale_parent_id_u" ON "_grants_v_blocks_min_card_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_id_card_gallery_cards_order_idx" ON "_grants_v_blocks_id_card_gallery_cards" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_id_card_gallery_cards_parent_id_idx" ON "_grants_v_blocks_id_card_gallery_cards" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_id_card_gallery_cards_mascot_idx" ON "_grants_v_blocks_id_card_gallery_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "_grants_v_blocks_id_card_gallery_cards_locales_locale_parent" ON "_grants_v_blocks_id_card_gallery_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_id_card_gallery_order_idx" ON "_grants_v_blocks_id_card_gallery" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_id_card_gallery_parent_id_idx" ON "_grants_v_blocks_id_card_gallery" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_id_card_gallery_path_idx" ON "_grants_v_blocks_id_card_gallery" USING btree ("_path");
  CREATE UNIQUE INDEX "_grants_v_blocks_id_card_gallery_locales_locale_parent_id_un" ON "_grants_v_blocks_id_card_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_two_column_block_order_idx" ON "_grants_v_blocks_two_column_block" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_two_column_block_parent_id_idx" ON "_grants_v_blocks_two_column_block" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_two_column_block_path_idx" ON "_grants_v_blocks_two_column_block" USING btree ("_path");
  CREATE UNIQUE INDEX "_grants_v_blocks_two_column_block_locales_locale_parent_id_u" ON "_grants_v_blocks_two_column_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_three_column_table_block_rows_order_idx" ON "_grants_v_blocks_three_column_table_block_rows" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_three_column_table_block_rows_parent_id_idx" ON "_grants_v_blocks_three_column_table_block_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_grants_v_blocks_three_column_table_block_rows_locales_local" ON "_grants_v_blocks_three_column_table_block_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_blocks_three_column_table_block_order_idx" ON "_grants_v_blocks_three_column_table_block" USING btree ("_order");
  CREATE INDEX "_grants_v_blocks_three_column_table_block_parent_id_idx" ON "_grants_v_blocks_three_column_table_block" USING btree ("_parent_id");
  CREATE INDEX "_grants_v_blocks_three_column_table_block_path_idx" ON "_grants_v_blocks_three_column_table_block" USING btree ("_path");
  CREATE UNIQUE INDEX "_grants_v_blocks_three_column_table_block_locales_locale_par" ON "_grants_v_blocks_three_column_table_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_parent_idx" ON "_grants_v" USING btree ("parent_id");
  CREATE INDEX "_grants_v_version_version_title_idx" ON "_grants_v" USING btree ("version_title");
  CREATE INDEX "_grants_v_version_version_grant_card_idx" ON "_grants_v" USING btree ("version_grant_card_id");
  CREATE INDEX "_grants_v_version_version_created_by_idx" ON "_grants_v" USING btree ("version_created_by_id");
  CREATE INDEX "_grants_v_version_version_updated_by_idx" ON "_grants_v" USING btree ("version_updated_by_id");
  CREATE INDEX "_grants_v_version_version_slug_idx" ON "_grants_v" USING btree ("version_slug");
  CREATE INDEX "_grants_v_version_meta_version_meta_image_idx" ON "_grants_v" USING btree ("version_meta_image_id");
  CREATE INDEX "_grants_v_version_version_folder_idx" ON "_grants_v" USING btree ("version_folder_id");
  CREATE INDEX "_grants_v_version_version_updated_at_idx" ON "_grants_v" USING btree ("version_updated_at");
  CREATE INDEX "_grants_v_version_version_created_at_idx" ON "_grants_v" USING btree ("version_created_at");
  CREATE INDEX "_grants_v_version_version_deleted_at_idx" ON "_grants_v" USING btree ("version_deleted_at");
  CREATE INDEX "_grants_v_version_version__status_idx" ON "_grants_v" USING btree ("version__status");
  CREATE INDEX "_grants_v_created_at_idx" ON "_grants_v" USING btree ("created_at");
  CREATE INDEX "_grants_v_updated_at_idx" ON "_grants_v" USING btree ("updated_at");
  CREATE INDEX "_grants_v_snapshot_idx" ON "_grants_v" USING btree ("snapshot");
  CREATE INDEX "_grants_v_published_locale_idx" ON "_grants_v" USING btree ("published_locale");
  CREATE INDEX "_grants_v_latest_idx" ON "_grants_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_grants_v_locales_locale_parent_id_unique" ON "_grants_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grants_v_rels_order_idx" ON "_grants_v_rels" USING btree ("order");
  CREATE INDEX "_grants_v_rels_parent_idx" ON "_grants_v_rels" USING btree ("parent_id");
  CREATE INDEX "_grants_v_rels_path_idx" ON "_grants_v_rels" USING btree ("path");
  CREATE INDEX "_grants_v_rels_grants_id_idx" ON "_grants_v_rels" USING btree ("grants_id");
  CREATE INDEX "_grants_v_rels_pages_id_idx" ON "_grants_v_rels" USING btree ("pages_id");
  CREATE INDEX "_grants_v_rels_blog_id_idx" ON "_grants_v_rels" USING btree ("blog_id");
  CREATE INDEX "_grants_v_rels_reports_id_idx" ON "_grants_v_rels" USING btree ("reports_id");
  CREATE INDEX "_grants_v_rels_mmedia_id_idx" ON "_grants_v_rels" USING btree ("mmedia_id");
  CREATE INDEX "_grants_v_rels_documents_id_idx" ON "_grants_v_rels" USING btree ("documents_id");
  CREATE INDEX "_grants_v_rels_etests_id_idx" ON "_grants_v_rels" USING btree ("etests_id");
  CREATE INDEX "_grants_v_rels_grantcards_id_idx" ON "_grants_v_rels" USING btree ("grantcards_id");
  CREATE INDEX "grantcards_grant_specs_order_idx" ON "grantcards_grant_specs" USING btree ("_order");
  CREATE INDEX "grantcards_grant_specs_parent_id_idx" ON "grantcards_grant_specs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "grantcards_grant_specs_locales_locale_parent_id_unique" ON "grantcards_grant_specs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "grantcards_card_buttons_order_idx" ON "grantcards_card_buttons" USING btree ("_order");
  CREATE INDEX "grantcards_card_buttons_parent_id_idx" ON "grantcards_card_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "grantcards_card_buttons_locales_locale_parent_id_unique" ON "grantcards_card_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "grantcards_active_period_idx" ON "grantcards" USING btree ("active_period");
  CREATE INDEX "grantcards_mascot_idx" ON "grantcards" USING btree ("mascot_id");
  CREATE INDEX "grantcards_created_by_idx" ON "grantcards" USING btree ("created_by_id");
  CREATE INDEX "grantcards_updated_by_idx" ON "grantcards" USING btree ("updated_by_id");
  CREATE INDEX "grantcards_slug_idx" ON "grantcards" USING btree ("slug");
  CREATE INDEX "grantcards_folder_idx" ON "grantcards" USING btree ("folder_id");
  CREATE INDEX "grantcards_updated_at_idx" ON "grantcards" USING btree ("updated_at");
  CREATE INDEX "grantcards_created_at_idx" ON "grantcards" USING btree ("created_at");
  CREATE INDEX "grantcards_deleted_at_idx" ON "grantcards" USING btree ("deleted_at");
  CREATE INDEX "grantcards__status_idx" ON "grantcards" USING btree ("_status");
  CREATE UNIQUE INDEX "grantcards_title_idx" ON "grantcards_locales" USING btree ("title","_locale");
  CREATE UNIQUE INDEX "grantcards_locales_locale_parent_id_unique" ON "grantcards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "grantcards_rels_order_idx" ON "grantcards_rels" USING btree ("order");
  CREATE INDEX "grantcards_rels_parent_idx" ON "grantcards_rels" USING btree ("parent_id");
  CREATE INDEX "grantcards_rels_path_idx" ON "grantcards_rels" USING btree ("path");
  CREATE INDEX "grantcards_rels_grants_id_idx" ON "grantcards_rels" USING btree ("grants_id");
  CREATE INDEX "grantcards_rels_pages_id_idx" ON "grantcards_rels" USING btree ("pages_id");
  CREATE INDEX "grantcards_rels_blog_id_idx" ON "grantcards_rels" USING btree ("blog_id");
  CREATE INDEX "grantcards_rels_reports_id_idx" ON "grantcards_rels" USING btree ("reports_id");
  CREATE INDEX "grantcards_rels_mmedia_id_idx" ON "grantcards_rels" USING btree ("mmedia_id");
  CREATE INDEX "grantcards_rels_documents_id_idx" ON "grantcards_rels" USING btree ("documents_id");
  CREATE INDEX "grantcards_rels_etests_id_idx" ON "grantcards_rels" USING btree ("etests_id");
  CREATE INDEX "_grantcards_v_version_grant_specs_order_idx" ON "_grantcards_v_version_grant_specs" USING btree ("_order");
  CREATE INDEX "_grantcards_v_version_grant_specs_parent_id_idx" ON "_grantcards_v_version_grant_specs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_grantcards_v_version_grant_specs_locales_locale_parent_id_u" ON "_grantcards_v_version_grant_specs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grantcards_v_version_card_buttons_order_idx" ON "_grantcards_v_version_card_buttons" USING btree ("_order");
  CREATE INDEX "_grantcards_v_version_card_buttons_parent_id_idx" ON "_grantcards_v_version_card_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_grantcards_v_version_card_buttons_locales_locale_parent_id_" ON "_grantcards_v_version_card_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grantcards_v_parent_idx" ON "_grantcards_v" USING btree ("parent_id");
  CREATE INDEX "_grantcards_v_version_version_active_period_idx" ON "_grantcards_v" USING btree ("version_active_period");
  CREATE INDEX "_grantcards_v_version_version_mascot_idx" ON "_grantcards_v" USING btree ("version_mascot_id");
  CREATE INDEX "_grantcards_v_version_version_created_by_idx" ON "_grantcards_v" USING btree ("version_created_by_id");
  CREATE INDEX "_grantcards_v_version_version_updated_by_idx" ON "_grantcards_v" USING btree ("version_updated_by_id");
  CREATE INDEX "_grantcards_v_version_version_slug_idx" ON "_grantcards_v" USING btree ("version_slug");
  CREATE INDEX "_grantcards_v_version_version_folder_idx" ON "_grantcards_v" USING btree ("version_folder_id");
  CREATE INDEX "_grantcards_v_version_version_updated_at_idx" ON "_grantcards_v" USING btree ("version_updated_at");
  CREATE INDEX "_grantcards_v_version_version_created_at_idx" ON "_grantcards_v" USING btree ("version_created_at");
  CREATE INDEX "_grantcards_v_version_version_deleted_at_idx" ON "_grantcards_v" USING btree ("version_deleted_at");
  CREATE INDEX "_grantcards_v_version_version__status_idx" ON "_grantcards_v" USING btree ("version__status");
  CREATE INDEX "_grantcards_v_created_at_idx" ON "_grantcards_v" USING btree ("created_at");
  CREATE INDEX "_grantcards_v_updated_at_idx" ON "_grantcards_v" USING btree ("updated_at");
  CREATE INDEX "_grantcards_v_snapshot_idx" ON "_grantcards_v" USING btree ("snapshot");
  CREATE INDEX "_grantcards_v_published_locale_idx" ON "_grantcards_v" USING btree ("published_locale");
  CREATE INDEX "_grantcards_v_latest_idx" ON "_grantcards_v" USING btree ("latest");
  CREATE INDEX "_grantcards_v_version_version_title_idx" ON "_grantcards_v_locales" USING btree ("version_title","_locale");
  CREATE UNIQUE INDEX "_grantcards_v_locales_locale_parent_id_unique" ON "_grantcards_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_grantcards_v_rels_order_idx" ON "_grantcards_v_rels" USING btree ("order");
  CREATE INDEX "_grantcards_v_rels_parent_idx" ON "_grantcards_v_rels" USING btree ("parent_id");
  CREATE INDEX "_grantcards_v_rels_path_idx" ON "_grantcards_v_rels" USING btree ("path");
  CREATE INDEX "_grantcards_v_rels_grants_id_idx" ON "_grantcards_v_rels" USING btree ("grants_id");
  CREATE INDEX "_grantcards_v_rels_pages_id_idx" ON "_grantcards_v_rels" USING btree ("pages_id");
  CREATE INDEX "_grantcards_v_rels_blog_id_idx" ON "_grantcards_v_rels" USING btree ("blog_id");
  CREATE INDEX "_grantcards_v_rels_reports_id_idx" ON "_grantcards_v_rels" USING btree ("reports_id");
  CREATE INDEX "_grantcards_v_rels_mmedia_id_idx" ON "_grantcards_v_rels" USING btree ("mmedia_id");
  CREATE INDEX "_grantcards_v_rels_documents_id_idx" ON "_grantcards_v_rels" USING btree ("documents_id");
  CREATE INDEX "_grantcards_v_rels_etests_id_idx" ON "_grantcards_v_rels" USING btree ("etests_id");
  CREATE INDEX "etests_crit_list_criteria_options_order_idx" ON "etests_crit_list_criteria_options" USING btree ("_order");
  CREATE INDEX "etests_crit_list_criteria_options_parent_id_idx" ON "etests_crit_list_criteria_options" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "etests_crit_list_criteria_options_locales_locale_parent_id_u" ON "etests_crit_list_criteria_options_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "etests_crit_list_criteria_order_idx" ON "etests_crit_list_criteria" USING btree ("_order");
  CREATE INDEX "etests_crit_list_criteria_parent_id_idx" ON "etests_crit_list_criteria" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "etests_crit_list_criteria_locales_locale_parent_id_unique" ON "etests_crit_list_criteria_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "etests_is_e_card_is_e_card_is_e_mascot_idx" ON "etests" USING btree ("is_e_card_is_e_mascot_id");
  CREATE INDEX "etests_not_e_card_not_e_card_not_e_mascot_idx" ON "etests" USING btree ("not_e_card_not_e_mascot_id");
  CREATE INDEX "etests_created_by_idx" ON "etests" USING btree ("created_by_id");
  CREATE INDEX "etests_updated_by_idx" ON "etests" USING btree ("updated_by_id");
  CREATE INDEX "etests_slug_idx" ON "etests" USING btree ("slug");
  CREATE INDEX "etests_updated_at_idx" ON "etests" USING btree ("updated_at");
  CREATE INDEX "etests_created_at_idx" ON "etests" USING btree ("created_at");
  CREATE INDEX "etests_deleted_at_idx" ON "etests" USING btree ("deleted_at");
  CREATE INDEX "etests__status_idx" ON "etests" USING btree ("_status");
  CREATE UNIQUE INDEX "etests_test_name_idx" ON "etests_locales" USING btree ("test_name","_locale");
  CREATE UNIQUE INDEX "etests_locales_locale_parent_id_unique" ON "etests_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "etests_rels_order_idx" ON "etests_rels" USING btree ("order");
  CREATE INDEX "etests_rels_parent_idx" ON "etests_rels" USING btree ("parent_id");
  CREATE INDEX "etests_rels_path_idx" ON "etests_rels" USING btree ("path");
  CREATE INDEX "etests_rels_grants_id_idx" ON "etests_rels" USING btree ("grants_id");
  CREATE INDEX "etests_rels_pages_id_idx" ON "etests_rels" USING btree ("pages_id");
  CREATE INDEX "etests_rels_blog_id_idx" ON "etests_rels" USING btree ("blog_id");
  CREATE INDEX "etests_rels_reports_id_idx" ON "etests_rels" USING btree ("reports_id");
  CREATE INDEX "etests_rels_mmedia_id_idx" ON "etests_rels" USING btree ("mmedia_id");
  CREATE INDEX "etests_rels_documents_id_idx" ON "etests_rels" USING btree ("documents_id");
  CREATE INDEX "etests_rels_etests_id_idx" ON "etests_rels" USING btree ("etests_id");
  CREATE INDEX "_etests_v_version_crit_list_criteria_options_order_idx" ON "_etests_v_version_crit_list_criteria_options" USING btree ("_order");
  CREATE INDEX "_etests_v_version_crit_list_criteria_options_parent_id_idx" ON "_etests_v_version_crit_list_criteria_options" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_etests_v_version_crit_list_criteria_options_locales_locale_" ON "_etests_v_version_crit_list_criteria_options_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_etests_v_version_crit_list_criteria_order_idx" ON "_etests_v_version_crit_list_criteria" USING btree ("_order");
  CREATE INDEX "_etests_v_version_crit_list_criteria_parent_id_idx" ON "_etests_v_version_crit_list_criteria" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_etests_v_version_crit_list_criteria_locales_locale_parent_i" ON "_etests_v_version_crit_list_criteria_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_etests_v_parent_idx" ON "_etests_v" USING btree ("parent_id");
  CREATE INDEX "_etests_v_version_is_e_card_version_is_e_card_is_e_masco_idx" ON "_etests_v" USING btree ("version_is_e_card_is_e_mascot_id");
  CREATE INDEX "_etests_v_version_not_e_card_version_not_e_card_not_e_ma_idx" ON "_etests_v" USING btree ("version_not_e_card_not_e_mascot_id");
  CREATE INDEX "_etests_v_version_version_created_by_idx" ON "_etests_v" USING btree ("version_created_by_id");
  CREATE INDEX "_etests_v_version_version_updated_by_idx" ON "_etests_v" USING btree ("version_updated_by_id");
  CREATE INDEX "_etests_v_version_version_slug_idx" ON "_etests_v" USING btree ("version_slug");
  CREATE INDEX "_etests_v_version_version_updated_at_idx" ON "_etests_v" USING btree ("version_updated_at");
  CREATE INDEX "_etests_v_version_version_created_at_idx" ON "_etests_v" USING btree ("version_created_at");
  CREATE INDEX "_etests_v_version_version_deleted_at_idx" ON "_etests_v" USING btree ("version_deleted_at");
  CREATE INDEX "_etests_v_version_version__status_idx" ON "_etests_v" USING btree ("version__status");
  CREATE INDEX "_etests_v_created_at_idx" ON "_etests_v" USING btree ("created_at");
  CREATE INDEX "_etests_v_updated_at_idx" ON "_etests_v" USING btree ("updated_at");
  CREATE INDEX "_etests_v_snapshot_idx" ON "_etests_v" USING btree ("snapshot");
  CREATE INDEX "_etests_v_published_locale_idx" ON "_etests_v" USING btree ("published_locale");
  CREATE INDEX "_etests_v_latest_idx" ON "_etests_v" USING btree ("latest");
  CREATE INDEX "_etests_v_version_version_test_name_idx" ON "_etests_v_locales" USING btree ("version_test_name","_locale");
  CREATE UNIQUE INDEX "_etests_v_locales_locale_parent_id_unique" ON "_etests_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_etests_v_rels_order_idx" ON "_etests_v_rels" USING btree ("order");
  CREATE INDEX "_etests_v_rels_parent_idx" ON "_etests_v_rels" USING btree ("parent_id");
  CREATE INDEX "_etests_v_rels_path_idx" ON "_etests_v_rels" USING btree ("path");
  CREATE INDEX "_etests_v_rels_grants_id_idx" ON "_etests_v_rels" USING btree ("grants_id");
  CREATE INDEX "_etests_v_rels_pages_id_idx" ON "_etests_v_rels" USING btree ("pages_id");
  CREATE INDEX "_etests_v_rels_blog_id_idx" ON "_etests_v_rels" USING btree ("blog_id");
  CREATE INDEX "_etests_v_rels_reports_id_idx" ON "_etests_v_rels" USING btree ("reports_id");
  CREATE INDEX "_etests_v_rels_mmedia_id_idx" ON "_etests_v_rels" USING btree ("mmedia_id");
  CREATE INDEX "_etests_v_rels_documents_id_idx" ON "_etests_v_rels" USING btree ("documents_id");
  CREATE INDEX "_etests_v_rels_etests_id_idx" ON "_etests_v_rels" USING btree ("etests_id");
  CREATE INDEX "pages_hero_buttons_order_idx" ON "pages_hero_buttons" USING btree ("_order");
  CREATE INDEX "pages_hero_buttons_parent_id_idx" ON "pages_hero_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_hero_buttons_locales_locale_parent_id_unique" ON "pages_hero_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_rich_content_block_order_idx" ON "pages_blocks_rich_content_block" USING btree ("_order");
  CREATE INDEX "pages_blocks_rich_content_block_parent_id_idx" ON "pages_blocks_rich_content_block" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_rich_content_block_path_idx" ON "pages_blocks_rich_content_block" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_rich_content_block_locales_locale_parent_id_uni" ON "pages_blocks_rich_content_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_secondarycta_cta_button_order_idx" ON "pages_blocks_secondarycta_cta_button" USING btree ("_order");
  CREATE INDEX "pages_blocks_secondarycta_cta_button_parent_id_idx" ON "pages_blocks_secondarycta_cta_button" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_secondarycta_cta_button_locales_locale_parent_i" ON "pages_blocks_secondarycta_cta_button_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_secondarycta_order_idx" ON "pages_blocks_secondarycta" USING btree ("_order");
  CREATE INDEX "pages_blocks_secondarycta_parent_id_idx" ON "pages_blocks_secondarycta" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_secondarycta_path_idx" ON "pages_blocks_secondarycta" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_secondarycta_locales_locale_parent_id_unique" ON "pages_blocks_secondarycta_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_mcol_info_block_multicols_order_idx" ON "pages_blocks_mcol_info_block_multicols" USING btree ("_order");
  CREATE INDEX "pages_blocks_mcol_info_block_multicols_parent_id_idx" ON "pages_blocks_mcol_info_block_multicols" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_mcol_info_block_multicols_locales_locale_parent" ON "pages_blocks_mcol_info_block_multicols_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_mcol_info_block_order_idx" ON "pages_blocks_mcol_info_block" USING btree ("_order");
  CREATE INDEX "pages_blocks_mcol_info_block_parent_id_idx" ON "pages_blocks_mcol_info_block" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_mcol_info_block_path_idx" ON "pages_blocks_mcol_info_block" USING btree ("_path");
  CREATE INDEX "pages_blocks_grant_card_grid_block_order_idx" ON "pages_blocks_grant_card_grid_block" USING btree ("_order");
  CREATE INDEX "pages_blocks_grant_card_grid_block_parent_id_idx" ON "pages_blocks_grant_card_grid_block" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_grant_card_grid_block_path_idx" ON "pages_blocks_grant_card_grid_block" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_grant_card_grid_block_locales_locale_parent_id_" ON "pages_blocks_grant_card_grid_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_mstep_process_steps_details_order_idx" ON "pages_blocks_mstep_process_steps_details" USING btree ("_order");
  CREATE INDEX "pages_blocks_mstep_process_steps_details_parent_id_idx" ON "pages_blocks_mstep_process_steps_details" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_mstep_process_steps_details_locales_locale_pare" ON "pages_blocks_mstep_process_steps_details_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_mstep_process_steps_order_idx" ON "pages_blocks_mstep_process_steps" USING btree ("_order");
  CREATE INDEX "pages_blocks_mstep_process_steps_parent_id_idx" ON "pages_blocks_mstep_process_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_mstep_process_steps_locales_locale_parent_id_un" ON "pages_blocks_mstep_process_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_mstep_process_order_idx" ON "pages_blocks_mstep_process" USING btree ("_order");
  CREATE INDEX "pages_blocks_mstep_process_parent_id_idx" ON "pages_blocks_mstep_process" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_mstep_process_path_idx" ON "pages_blocks_mstep_process" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_mstep_process_locales_locale_parent_id_unique" ON "pages_blocks_mstep_process_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_comparison_blk_lft_grp_lft_points_order_idx" ON "pages_blocks_comparison_blk_lft_grp_lft_points" USING btree ("_order");
  CREATE INDEX "pages_blocks_comparison_blk_lft_grp_lft_points_parent_id_idx" ON "pages_blocks_comparison_blk_lft_grp_lft_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_comparison_blk_lft_grp_lft_points_locales_local" ON "pages_blocks_comparison_blk_lft_grp_lft_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_comparison_blk_rt_grp_rt_points_order_idx" ON "pages_blocks_comparison_blk_rt_grp_rt_points" USING btree ("_order");
  CREATE INDEX "pages_blocks_comparison_blk_rt_grp_rt_points_parent_id_idx" ON "pages_blocks_comparison_blk_rt_grp_rt_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_comparison_blk_rt_grp_rt_points_locales_locale_" ON "pages_blocks_comparison_blk_rt_grp_rt_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_comparison_blk_buttons_order_idx" ON "pages_blocks_comparison_blk_buttons" USING btree ("_order");
  CREATE INDEX "pages_blocks_comparison_blk_buttons_parent_id_idx" ON "pages_blocks_comparison_blk_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_comparison_blk_buttons_locales_locale_parent_id" ON "pages_blocks_comparison_blk_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_comparison_blk_order_idx" ON "pages_blocks_comparison_blk" USING btree ("_order");
  CREATE INDEX "pages_blocks_comparison_blk_parent_id_idx" ON "pages_blocks_comparison_blk" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_comparison_blk_path_idx" ON "pages_blocks_comparison_blk" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_comparison_blk_locales_locale_parent_id_unique" ON "pages_blocks_comparison_blk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_ylw_deck_cards_links_order_idx" ON "pages_blocks_ylw_deck_cards_links" USING btree ("_order");
  CREATE INDEX "pages_blocks_ylw_deck_cards_links_parent_id_idx" ON "pages_blocks_ylw_deck_cards_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_ylw_deck_cards_links_locales_locale_parent_id_u" ON "pages_blocks_ylw_deck_cards_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_ylw_deck_cards_order_idx" ON "pages_blocks_ylw_deck_cards" USING btree ("_order");
  CREATE INDEX "pages_blocks_ylw_deck_cards_parent_id_idx" ON "pages_blocks_ylw_deck_cards" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_ylw_deck_cards_mascot_idx" ON "pages_blocks_ylw_deck_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "pages_blocks_ylw_deck_cards_locales_locale_parent_id_unique" ON "pages_blocks_ylw_deck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_ylw_deck_order_idx" ON "pages_blocks_ylw_deck" USING btree ("_order");
  CREATE INDEX "pages_blocks_ylw_deck_parent_id_idx" ON "pages_blocks_ylw_deck" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_ylw_deck_path_idx" ON "pages_blocks_ylw_deck" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_ylw_deck_locales_locale_parent_id_unique" ON "pages_blocks_ylw_deck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_tags_order_idx" ON "pages_blocks_feat_crd_tags" USING btree ("_order");
  CREATE INDEX "pages_blocks_feat_crd_tags_parent_id_idx" ON "pages_blocks_feat_crd_tags" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_feat_crd_tags_locales_locale_parent_id_unique" ON "pages_blocks_feat_crd_tags_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_order_idx" ON "pages_blocks_feat_crd" USING btree ("_order");
  CREATE INDEX "pages_blocks_feat_crd_parent_id_idx" ON "pages_blocks_feat_crd" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_path_idx" ON "pages_blocks_feat_crd" USING btree ("_path");
  CREATE INDEX "pages_blocks_feat_crd_image_idx" ON "pages_blocks_feat_crd" USING btree ("image_id");
  CREATE UNIQUE INDEX "pages_blocks_feat_crd_locales_locale_parent_id_unique" ON "pages_blocks_feat_crd_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_acc_feat_crds_order_idx" ON "pages_blocks_feat_crd_acc_feat_crds" USING btree ("_order");
  CREATE INDEX "pages_blocks_feat_crd_acc_feat_crds_parent_id_idx" ON "pages_blocks_feat_crd_acc_feat_crds" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_acc_feat_crds_mascot_idx" ON "pages_blocks_feat_crd_acc_feat_crds" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "pages_blocks_feat_crd_acc_feat_crds_locales_locale_parent_id" ON "pages_blocks_feat_crd_acc_feat_crds_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_acc_order_idx" ON "pages_blocks_feat_crd_acc" USING btree ("_order");
  CREATE INDEX "pages_blocks_feat_crd_acc_parent_id_idx" ON "pages_blocks_feat_crd_acc" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_feat_crd_acc_path_idx" ON "pages_blocks_feat_crd_acc" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_feat_crd_acc_locales_locale_parent_id_unique" ON "pages_blocks_feat_crd_acc_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_list_crd_dck_cards_tags_order_idx" ON "pages_blocks_list_crd_dck_cards_tags" USING btree ("_order");
  CREATE INDEX "pages_blocks_list_crd_dck_cards_tags_parent_id_idx" ON "pages_blocks_list_crd_dck_cards_tags" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_list_crd_dck_cards_tags_locales_locale_parent_i" ON "pages_blocks_list_crd_dck_cards_tags_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_list_crd_dck_cards_order_idx" ON "pages_blocks_list_crd_dck_cards" USING btree ("_order");
  CREATE INDEX "pages_blocks_list_crd_dck_cards_parent_id_idx" ON "pages_blocks_list_crd_dck_cards" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_list_crd_dck_cards_image_idx" ON "pages_blocks_list_crd_dck_cards" USING btree ("image_id");
  CREATE UNIQUE INDEX "pages_blocks_list_crd_dck_cards_locales_locale_parent_id_uni" ON "pages_blocks_list_crd_dck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_list_crd_dck_buttons_order_idx" ON "pages_blocks_list_crd_dck_buttons" USING btree ("_order");
  CREATE INDEX "pages_blocks_list_crd_dck_buttons_parent_id_idx" ON "pages_blocks_list_crd_dck_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_list_crd_dck_buttons_locales_locale_parent_id_u" ON "pages_blocks_list_crd_dck_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_list_crd_dck_order_idx" ON "pages_blocks_list_crd_dck" USING btree ("_order");
  CREATE INDEX "pages_blocks_list_crd_dck_parent_id_idx" ON "pages_blocks_list_crd_dck" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_list_crd_dck_path_idx" ON "pages_blocks_list_crd_dck" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_list_crd_dck_locales_locale_parent_id_unique" ON "pages_blocks_list_crd_dck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_faq_blk_faqs_order_idx" ON "pages_blocks_faq_blk_faqs" USING btree ("_order");
  CREATE INDEX "pages_blocks_faq_blk_faqs_parent_id_idx" ON "pages_blocks_faq_blk_faqs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_faq_blk_faqs_locales_locale_parent_id_unique" ON "pages_blocks_faq_blk_faqs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_faq_blk_order_idx" ON "pages_blocks_faq_blk" USING btree ("_order");
  CREATE INDEX "pages_blocks_faq_blk_parent_id_idx" ON "pages_blocks_faq_blk" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_faq_blk_path_idx" ON "pages_blocks_faq_blk" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_faq_blk_locales_locale_parent_id_unique" ON "pages_blocks_faq_blk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_pink_puffy_top_row_order_idx" ON "pages_blocks_pink_puffy_top_row" USING btree ("_order");
  CREATE INDEX "pages_blocks_pink_puffy_top_row_parent_id_idx" ON "pages_blocks_pink_puffy_top_row" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_pink_puffy_top_row_locales_locale_parent_id_uni" ON "pages_blocks_pink_puffy_top_row_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_pink_puffy_bot_row_order_idx" ON "pages_blocks_pink_puffy_bot_row" USING btree ("_order");
  CREATE INDEX "pages_blocks_pink_puffy_bot_row_parent_id_idx" ON "pages_blocks_pink_puffy_bot_row" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_pink_puffy_bot_row_locales_locale_parent_id_uni" ON "pages_blocks_pink_puffy_bot_row_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_pink_puffy_links_order_idx" ON "pages_blocks_pink_puffy_links" USING btree ("_order");
  CREATE INDEX "pages_blocks_pink_puffy_links_parent_id_idx" ON "pages_blocks_pink_puffy_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_pink_puffy_links_locales_locale_parent_id_uniqu" ON "pages_blocks_pink_puffy_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_pink_puffy_order_idx" ON "pages_blocks_pink_puffy" USING btree ("_order");
  CREATE INDEX "pages_blocks_pink_puffy_parent_id_idx" ON "pages_blocks_pink_puffy" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_pink_puffy_path_idx" ON "pages_blocks_pink_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "pages_blocks_pink_puffy_locales_locale_parent_id_unique" ON "pages_blocks_pink_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_blocks_beige_puffy_items_order_idx" ON "pages_blocks_beige_puffy_items" USING btree ("_order");
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // no-op
}
