import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE UNIQUE INDEX "_mmedia_v_locales_locale_parent_id_unique" ON "_mmedia_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_mmedia_v_rels_order_idx" ON "_mmedia_v_rels" USING btree ("order");
  CREATE INDEX "_mmedia_v_rels_parent_idx" ON "_mmedia_v_rels" USING btree ("parent_id");
  CREATE INDEX "_mmedia_v_rels_path_idx" ON "_mmedia_v_rels" USING btree ("path");
  CREATE INDEX "_mmedia_v_rels_doctypes_id_idx" ON "_mmedia_v_rels" USING btree ("doctypes_id");
  CREATE INDEX "_mmedia_v_rels_grants_id_idx" ON "_mmedia_v_rels" USING btree ("grants_id");
  CREATE INDEX "_mmedia_v_rels_pages_id_idx" ON "_mmedia_v_rels" USING btree ("pages_id");
  CREATE INDEX "_mmedia_v_rels_blog_id_idx" ON "_mmedia_v_rels" USING btree ("blog_id");
  CREATE INDEX "_mmedia_v_rels_reports_id_idx" ON "_mmedia_v_rels" USING btree ("reports_id");
  CREATE INDEX "_mmedia_v_rels_mmedia_id_idx" ON "_mmedia_v_rels" USING btree ("mmedia_id");
  CREATE INDEX "_mmedia_v_rels_documents_id_idx" ON "_mmedia_v_rels" USING btree ("documents_id");
  CREATE INDEX "_mmedia_v_rels_etests_id_idx" ON "_mmedia_v_rels" USING btree ("etests_id");
  CREATE INDEX "_mmedia_v_rels_grantcards_id_idx" ON "_mmedia_v_rels" USING btree ("grantcards_id");
  CREATE INDEX "doctypes_updated_at_idx" ON "doctypes" USING btree ("updated_at");
  CREATE INDEX "doctypes_created_at_idx" ON "doctypes" USING btree ("created_at");
  CREATE INDEX "doctypes_deleted_at_idx" ON "doctypes" USING btree ("deleted_at");
  CREATE UNIQUE INDEX "doctypes_locales_locale_parent_id_unique" ON "doctypes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "media_cloud_folder_idx" ON "media_cloud" USING btree ("folder_id");
  CREATE INDEX "media_cloud_updated_at_idx" ON "media_cloud" USING btree ("updated_at");
  CREATE INDEX "media_cloud_created_at_idx" ON "media_cloud" USING btree ("created_at");
  CREATE INDEX "media_cloud_deleted_at_idx" ON "media_cloud" USING btree ("deleted_at");
  CREATE UNIQUE INDEX "media_cloud_filename_idx" ON "media_cloud" USING btree ("filename");
  CREATE INDEX "media_cloud_sizes_thumbnail_sizes_thumbnail_filename_idx" ON "media_cloud" USING btree ("sizes_thumbnail_filename");
  CREATE INDEX "media_cloud_sizes_small_sizes_small_filename_idx" ON "media_cloud" USING btree ("sizes_small_filename");
  CREATE INDEX "media_cloud_sizes_medium_sizes_medium_filename_idx" ON "media_cloud" USING btree ("sizes_medium_filename");
  CREATE INDEX "media_cloud_sizes_large_sizes_large_filename_idx" ON "media_cloud" USING btree ("sizes_large_filename");
  CREATE INDEX "media_cloud_sizes_xlarge_sizes_xlarge_filename_idx" ON "media_cloud" USING btree ("sizes_xlarge_filename");
  CREATE INDEX "media_cloud_sizes_og_image_sizes_og_image_filename_idx" ON "media_cloud" USING btree ("sizes_og_image_filename");
  CREATE UNIQUE INDEX "media_cloud_locales_locale_parent_id_unique" ON "media_cloud_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "asset_cloud_folder_idx" ON "asset_cloud" USING btree ("folder_id");
  CREATE INDEX "asset_cloud_updated_at_idx" ON "asset_cloud" USING btree ("updated_at");
  CREATE INDEX "asset_cloud_created_at_idx" ON "asset_cloud" USING btree ("created_at");
  CREATE INDEX "asset_cloud_deleted_at_idx" ON "asset_cloud" USING btree ("deleted_at");
  CREATE UNIQUE INDEX "asset_cloud_filename_idx" ON "asset_cloud" USING btree ("filename");
  CREATE INDEX "asset_cloud_sizes_thumbnail_sizes_thumbnail_filename_idx" ON "asset_cloud" USING btree ("sizes_thumbnail_filename");
  CREATE INDEX "asset_cloud_sizes_small_sizes_small_filename_idx" ON "asset_cloud" USING btree ("sizes_small_filename");
  CREATE INDEX "asset_cloud_sizes_medium_sizes_medium_filename_idx" ON "asset_cloud" USING btree ("sizes_medium_filename");
  CREATE INDEX "asset_cloud_sizes_large_sizes_large_filename_idx" ON "asset_cloud" USING btree ("sizes_large_filename");
  CREATE INDEX "asset_cloud_sizes_xlarge_sizes_xlarge_filename_idx" ON "asset_cloud" USING btree ("sizes_xlarge_filename");
  CREATE UNIQUE INDEX "asset_cloud_locales_locale_parent_id_unique" ON "asset_cloud_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "documents_folder_idx" ON "documents" USING btree ("folder_id");
  CREATE INDEX "documents_updated_at_idx" ON "documents" USING btree ("updated_at");
  CREATE INDEX "documents_created_at_idx" ON "documents" USING btree ("created_at");
  CREATE INDEX "documents_deleted_at_idx" ON "documents" USING btree ("deleted_at");
  CREATE UNIQUE INDEX "documents_filename_idx" ON "documents" USING btree ("filename");
  CREATE UNIQUE INDEX "documents_locales_locale_parent_id_unique" ON "documents_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "users_assigned_languages_order_idx" ON "users_assigned_languages" USING btree ("order");
  CREATE INDEX "users_assigned_languages_parent_idx" ON "users_assigned_languages" USING btree ("parent_id");
  CREATE INDEX "users_sessions_order_idx" ON "users_sessions" USING btree ("_order");
  CREATE INDEX "users_sessions_parent_id_idx" ON "users_sessions" USING btree ("_parent_id");
  CREATE INDEX "users_avatar_idx" ON "users" USING btree ("avatar_id");
  CREATE INDEX "users_updated_at_idx" ON "users" USING btree ("updated_at");
  CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");
  CREATE UNIQUE INDEX "users_email_idx" ON "users" USING btree ("email");
  CREATE UNIQUE INDEX "redirects_from_idx" ON "redirects" USING btree ("from");
  CREATE INDEX "redirects_updated_at_idx" ON "redirects" USING btree ("updated_at");
  CREATE INDEX "redirects_created_at_idx" ON "redirects" USING btree ("created_at");
  CREATE INDEX "redirects_rels_order_idx" ON "redirects_rels" USING btree ("order");
  CREATE INDEX "redirects_rels_parent_idx" ON "redirects_rels" USING btree ("parent_id");
  CREATE INDEX "redirects_rels_path_idx" ON "redirects_rels" USING btree ("path");
  CREATE INDEX "redirects_rels_pages_id_idx" ON "redirects_rels" USING btree ("pages_id");
  CREATE INDEX "redirects_rels_reports_id_idx" ON "redirects_rels" USING btree ("reports_id");
  CREATE INDEX "redirects_rels_blog_id_idx" ON "redirects_rels" USING btree ("blog_id");
  CREATE INDEX "redirects_rels_mmedia_id_idx" ON "redirects_rels" USING btree ("mmedia_id");
  CREATE INDEX "redirects_rels_grants_id_idx" ON "redirects_rels" USING btree ("grants_id");
  CREATE INDEX "forms_blocks_checkbox_order_idx" ON "forms_blocks_checkbox" USING btree ("_order");
  CREATE INDEX "forms_blocks_checkbox_parent_id_idx" ON "forms_blocks_checkbox" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_checkbox_path_idx" ON "forms_blocks_checkbox" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_checkbox_locales_locale_parent_id_unique" ON "forms_blocks_checkbox_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_country_order_idx" ON "forms_blocks_country" USING btree ("_order");
  CREATE INDEX "forms_blocks_country_parent_id_idx" ON "forms_blocks_country" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_country_path_idx" ON "forms_blocks_country" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_country_locales_locale_parent_id_unique" ON "forms_blocks_country_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_email_order_idx" ON "forms_blocks_email" USING btree ("_order");
  CREATE INDEX "forms_blocks_email_parent_id_idx" ON "forms_blocks_email" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_email_path_idx" ON "forms_blocks_email" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_email_locales_locale_parent_id_unique" ON "forms_blocks_email_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_message_order_idx" ON "forms_blocks_message" USING btree ("_order");
  CREATE INDEX "forms_blocks_message_parent_id_idx" ON "forms_blocks_message" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_message_path_idx" ON "forms_blocks_message" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_message_locales_locale_parent_id_unique" ON "forms_blocks_message_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_number_order_idx" ON "forms_blocks_number" USING btree ("_order");
  CREATE INDEX "forms_blocks_number_parent_id_idx" ON "forms_blocks_number" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_number_path_idx" ON "forms_blocks_number" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_number_locales_locale_parent_id_unique" ON "forms_blocks_number_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_select_options_order_idx" ON "forms_blocks_select_options" USING btree ("_order");
  CREATE INDEX "forms_blocks_select_options_parent_id_idx" ON "forms_blocks_select_options" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "forms_blocks_select_options_locales_locale_parent_id_unique" ON "forms_blocks_select_options_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_select_order_idx" ON "forms_blocks_select" USING btree ("_order");
  CREATE INDEX "forms_blocks_select_parent_id_idx" ON "forms_blocks_select" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_select_path_idx" ON "forms_blocks_select" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_select_locales_locale_parent_id_unique" ON "forms_blocks_select_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_state_order_idx" ON "forms_blocks_state" USING btree ("_order");
  CREATE INDEX "forms_blocks_state_parent_id_idx" ON "forms_blocks_state" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_state_path_idx" ON "forms_blocks_state" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_state_locales_locale_parent_id_unique" ON "forms_blocks_state_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_text_order_idx" ON "forms_blocks_text" USING btree ("_order");
  CREATE INDEX "forms_blocks_text_parent_id_idx" ON "forms_blocks_text" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_text_path_idx" ON "forms_blocks_text" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_text_locales_locale_parent_id_unique" ON "forms_blocks_text_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_blocks_textarea_order_idx" ON "forms_blocks_textarea" USING btree ("_order");
  CREATE INDEX "forms_blocks_textarea_parent_id_idx" ON "forms_blocks_textarea" USING btree ("_parent_id");
  CREATE INDEX "forms_blocks_textarea_path_idx" ON "forms_blocks_textarea" USING btree ("_path");
  CREATE UNIQUE INDEX "forms_blocks_textarea_locales_locale_parent_id_unique" ON "forms_blocks_textarea_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_emails_order_idx" ON "forms_emails" USING btree ("_order");
  CREATE INDEX "forms_emails_parent_id_idx" ON "forms_emails" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "forms_emails_locales_locale_parent_id_unique" ON "forms_emails_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "forms_updated_at_idx" ON "forms" USING btree ("updated_at");
  CREATE INDEX "forms_created_at_idx" ON "forms" USING btree ("created_at");
  CREATE UNIQUE INDEX "forms_locales_locale_parent_id_unique" ON "forms_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "form_submissions_submission_data_order_idx" ON "form_submissions_submission_data" USING btree ("_order");
  CREATE INDEX "form_submissions_submission_data_parent_id_idx" ON "form_submissions_submission_data" USING btree ("_parent_id");
  CREATE INDEX "form_submissions_form_idx" ON "form_submissions" USING btree ("form_id");
  CREATE INDEX "form_submissions_updated_at_idx" ON "form_submissions" USING btree ("updated_at");
  CREATE INDEX "form_submissions_created_at_idx" ON "form_submissions" USING btree ("created_at");
  CREATE INDEX "search_categories_order_idx" ON "search_categories" USING btree ("_order");
  CREATE INDEX "search_categories_parent_id_idx" ON "search_categories" USING btree ("_parent_id");
  CREATE INDEX "search_slug_idx" ON "search" USING btree ("slug");
  CREATE INDEX "search_author_idx" ON "search" USING btree ("author");
  CREATE INDEX "search_tags_idx" ON "search" USING btree ("tags");
  CREATE INDEX "search_published_date_idx" ON "search" USING btree ("published_date");
  CREATE INDEX "search_updated_at_idx" ON "search" USING btree ("updated_at");
  CREATE INDEX "search_created_at_idx" ON "search" USING btree ("created_at");
  CREATE UNIQUE INDEX "search_locales_locale_parent_id_unique" ON "search_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "search_rels_order_idx" ON "search_rels" USING btree ("order");
  CREATE INDEX "search_rels_parent_idx" ON "search_rels" USING btree ("parent_id");
  CREATE INDEX "search_rels_path_idx" ON "search_rels" USING btree ("path");
  CREATE INDEX "search_rels_pages_id_idx" ON "search_rels" USING btree ("pages_id");
  CREATE INDEX "search_rels_reports_id_idx" ON "search_rels" USING btree ("reports_id");
  CREATE INDEX "search_rels_blog_id_idx" ON "search_rels" USING btree ("blog_id");
  CREATE INDEX "search_rels_mmedia_id_idx" ON "search_rels" USING btree ("mmedia_id");
  CREATE INDEX "search_rels_grants_id_idx" ON "search_rels" USING btree ("grants_id");
  CREATE INDEX "search_rels_media_cloud_id_idx" ON "search_rels" USING btree ("media_cloud_id");
  CREATE INDEX "search_rels_asset_cloud_id_idx" ON "search_rels" USING btree ("asset_cloud_id");
  CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload_kv" USING btree ("key");
  CREATE INDEX "payload_folders_folder_type_order_idx" ON "payload_folders_folder_type" USING btree ("order");
  CREATE INDEX "payload_folders_folder_type_parent_idx" ON "payload_folders_folder_type" USING btree ("parent_id");
  CREATE INDEX "payload_folders_name_idx" ON "payload_folders" USING btree ("name");
  CREATE INDEX "payload_folders_folder_idx" ON "payload_folders" USING btree ("folder_id");
  CREATE INDEX "payload_folders_updated_at_idx" ON "payload_folders" USING btree ("updated_at");
  CREATE INDEX "payload_folders_created_at_idx" ON "payload_folders" USING btree ("created_at");
  CREATE INDEX "payload_locked_documents_global_slug_idx" ON "payload_locked_documents" USING btree ("global_slug");
  CREATE INDEX "payload_locked_documents_updated_at_idx" ON "payload_locked_documents" USING btree ("updated_at");
  CREATE INDEX "payload_locked_documents_created_at_idx" ON "payload_locked_documents" USING btree ("created_at");
  CREATE INDEX "payload_locked_documents_rels_order_idx" ON "payload_locked_documents_rels" USING btree ("order");
  CREATE INDEX "payload_locked_documents_rels_parent_idx" ON "payload_locked_documents_rels" USING btree ("parent_id");
  CREATE INDEX "payload_locked_documents_rels_path_idx" ON "payload_locked_documents_rels" USING btree ("path");
  CREATE INDEX "payload_locked_documents_rels_grants_id_idx" ON "payload_locked_documents_rels" USING btree ("grants_id");
  CREATE INDEX "payload_locked_documents_rels_grantcards_id_idx" ON "payload_locked_documents_rels" USING btree ("grantcards_id");
  CREATE INDEX "payload_locked_documents_rels_etests_id_idx" ON "payload_locked_documents_rels" USING btree ("etests_id");
  CREATE INDEX "payload_locked_documents_rels_pages_id_idx" ON "payload_locked_documents_rels" USING btree ("pages_id");
  CREATE INDEX "payload_locked_documents_rels_blog_id_idx" ON "payload_locked_documents_rels" USING btree ("blog_id");
  CREATE INDEX "payload_locked_documents_rels_reports_id_idx" ON "payload_locked_documents_rels" USING btree ("reports_id");
  CREATE INDEX "payload_locked_documents_rels_mmedia_id_idx" ON "payload_locked_documents_rels" USING btree ("mmedia_id");
  CREATE INDEX "payload_locked_documents_rels_doctypes_id_idx" ON "payload_locked_documents_rels" USING btree ("doctypes_id");
  CREATE INDEX "payload_locked_documents_rels_media_cloud_id_idx" ON "payload_locked_documents_rels" USING btree ("media_cloud_id");
  CREATE INDEX "payload_locked_documents_rels_asset_cloud_id_idx" ON "payload_locked_documents_rels" USING btree ("asset_cloud_id");
  CREATE INDEX "payload_locked_documents_rels_documents_id_idx" ON "payload_locked_documents_rels" USING btree ("documents_id");
  CREATE INDEX "payload_locked_documents_rels_users_id_idx" ON "payload_locked_documents_rels" USING btree ("users_id");
  CREATE INDEX "payload_locked_documents_rels_redirects_id_idx" ON "payload_locked_documents_rels" USING btree ("redirects_id");
  CREATE INDEX "payload_locked_documents_rels_forms_id_idx" ON "payload_locked_documents_rels" USING btree ("forms_id");
  CREATE INDEX "payload_locked_documents_rels_form_submissions_id_idx" ON "payload_locked_documents_rels" USING btree ("form_submissions_id");
  CREATE INDEX "payload_locked_documents_rels_search_id_idx" ON "payload_locked_documents_rels" USING btree ("search_id");
  CREATE INDEX "payload_locked_documents_rels_payload_folders_id_idx" ON "payload_locked_documents_rels" USING btree ("payload_folders_id");
  CREATE INDEX "payload_preferences_key_idx" ON "payload_preferences" USING btree ("key");
  CREATE INDEX "payload_preferences_updated_at_idx" ON "payload_preferences" USING btree ("updated_at");
  CREATE INDEX "payload_preferences_created_at_idx" ON "payload_preferences" USING btree ("created_at");
  CREATE INDEX "payload_preferences_rels_order_idx" ON "payload_preferences_rels" USING btree ("order");
  CREATE INDEX "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" USING btree ("parent_id");
  CREATE INDEX "payload_preferences_rels_path_idx" ON "payload_preferences_rels" USING btree ("path");
  CREATE INDEX "payload_preferences_rels_users_id_idx" ON "payload_preferences_rels" USING btree ("users_id");
  CREATE INDEX "payload_migrations_updated_at_idx" ON "payload_migrations" USING btree ("updated_at");
  CREATE INDEX "payload_migrations_created_at_idx" ON "payload_migrations" USING btree ("created_at");
  CREATE INDEX "homepage_cta_button_order_idx" ON "homepage_cta_button" USING btree ("_order");
  CREATE INDEX "homepage_cta_button_parent_id_idx" ON "homepage_cta_button" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_cta_button_locales_locale_parent_id_unique" ON "homepage_cta_button_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_rich_content_block_order_idx" ON "homepage_blocks_rich_content_block" USING btree ("_order");
  CREATE INDEX "homepage_blocks_rich_content_block_parent_id_idx" ON "homepage_blocks_rich_content_block" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_rich_content_block_path_idx" ON "homepage_blocks_rich_content_block" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_rich_content_block_locales_locale_parent_id_" ON "homepage_blocks_rich_content_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_secondarycta_cta_button_order_idx" ON "homepage_blocks_secondarycta_cta_button" USING btree ("_order");
  CREATE INDEX "homepage_blocks_secondarycta_cta_button_parent_id_idx" ON "homepage_blocks_secondarycta_cta_button" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_secondarycta_cta_button_locales_locale_paren" ON "homepage_blocks_secondarycta_cta_button_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_secondarycta_order_idx" ON "homepage_blocks_secondarycta" USING btree ("_order");
  CREATE INDEX "homepage_blocks_secondarycta_parent_id_idx" ON "homepage_blocks_secondarycta" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_secondarycta_path_idx" ON "homepage_blocks_secondarycta" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_secondarycta_locales_locale_parent_id_unique" ON "homepage_blocks_secondarycta_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_mcol_info_block_multicols_order_idx" ON "homepage_blocks_mcol_info_block_multicols" USING btree ("_order");
  CREATE INDEX "homepage_blocks_mcol_info_block_multicols_parent_id_idx" ON "homepage_blocks_mcol_info_block_multicols" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_mcol_info_block_multicols_locales_locale_par" ON "homepage_blocks_mcol_info_block_multicols_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_mcol_info_block_order_idx" ON "homepage_blocks_mcol_info_block" USING btree ("_order");
  CREATE INDEX "homepage_blocks_mcol_info_block_parent_id_idx" ON "homepage_blocks_mcol_info_block" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_mcol_info_block_path_idx" ON "homepage_blocks_mcol_info_block" USING btree ("_path");
  CREATE INDEX "homepage_blocks_grant_card_grid_block_order_idx" ON "homepage_blocks_grant_card_grid_block" USING btree ("_order");
  CREATE INDEX "homepage_blocks_grant_card_grid_block_parent_id_idx" ON "homepage_blocks_grant_card_grid_block" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_grant_card_grid_block_path_idx" ON "homepage_blocks_grant_card_grid_block" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_grant_card_grid_block_locales_locale_parent_" ON "homepage_blocks_grant_card_grid_block_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_mstep_process_steps_details_order_idx" ON "homepage_blocks_mstep_process_steps_details" USING btree ("_order");
  CREATE INDEX "homepage_blocks_mstep_process_steps_details_parent_id_idx" ON "homepage_blocks_mstep_process_steps_details" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_mstep_process_steps_details_locales_locale_p" ON "homepage_blocks_mstep_process_steps_details_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_mstep_process_steps_order_idx" ON "homepage_blocks_mstep_process_steps" USING btree ("_order");
  CREATE INDEX "homepage_blocks_mstep_process_steps_parent_id_idx" ON "homepage_blocks_mstep_process_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_mstep_process_steps_locales_locale_parent_id" ON "homepage_blocks_mstep_process_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_mstep_process_order_idx" ON "homepage_blocks_mstep_process" USING btree ("_order");
  CREATE INDEX "homepage_blocks_mstep_process_parent_id_idx" ON "homepage_blocks_mstep_process" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_mstep_process_path_idx" ON "homepage_blocks_mstep_process" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_mstep_process_locales_locale_parent_id_uniqu" ON "homepage_blocks_mstep_process_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_comparison_blk_lft_grp_lft_points_order_idx" ON "homepage_blocks_comparison_blk_lft_grp_lft_points" USING btree ("_order");
  CREATE INDEX "homepage_blocks_comparison_blk_lft_grp_lft_points_parent_id_idx" ON "homepage_blocks_comparison_blk_lft_grp_lft_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_comparison_blk_lft_grp_lft_points_locales_lo" ON "homepage_blocks_comparison_blk_lft_grp_lft_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_comparison_blk_rt_grp_rt_points_order_idx" ON "homepage_blocks_comparison_blk_rt_grp_rt_points" USING btree ("_order");
  CREATE INDEX "homepage_blocks_comparison_blk_rt_grp_rt_points_parent_id_idx" ON "homepage_blocks_comparison_blk_rt_grp_rt_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_comparison_blk_rt_grp_rt_points_locales_loca" ON "homepage_blocks_comparison_blk_rt_grp_rt_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_comparison_blk_buttons_order_idx" ON "homepage_blocks_comparison_blk_buttons" USING btree ("_order");
  CREATE INDEX "homepage_blocks_comparison_blk_buttons_parent_id_idx" ON "homepage_blocks_comparison_blk_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_comparison_blk_buttons_locales_locale_parent" ON "homepage_blocks_comparison_blk_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_comparison_blk_order_idx" ON "homepage_blocks_comparison_blk" USING btree ("_order");
  CREATE INDEX "homepage_blocks_comparison_blk_parent_id_idx" ON "homepage_blocks_comparison_blk" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_comparison_blk_path_idx" ON "homepage_blocks_comparison_blk" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_comparison_blk_locales_locale_parent_id_uniq" ON "homepage_blocks_comparison_blk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_ylw_deck_cards_links_order_idx" ON "homepage_blocks_ylw_deck_cards_links" USING btree ("_order");
  CREATE INDEX "homepage_blocks_ylw_deck_cards_links_parent_id_idx" ON "homepage_blocks_ylw_deck_cards_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_ylw_deck_cards_links_locales_locale_parent_i" ON "homepage_blocks_ylw_deck_cards_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_ylw_deck_cards_order_idx" ON "homepage_blocks_ylw_deck_cards" USING btree ("_order");
  CREATE INDEX "homepage_blocks_ylw_deck_cards_parent_id_idx" ON "homepage_blocks_ylw_deck_cards" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_ylw_deck_cards_mascot_idx" ON "homepage_blocks_ylw_deck_cards" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "homepage_blocks_ylw_deck_cards_locales_locale_parent_id_uniq" ON "homepage_blocks_ylw_deck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_ylw_deck_order_idx" ON "homepage_blocks_ylw_deck" USING btree ("_order");
  CREATE INDEX "homepage_blocks_ylw_deck_parent_id_idx" ON "homepage_blocks_ylw_deck" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_ylw_deck_path_idx" ON "homepage_blocks_ylw_deck" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_ylw_deck_locales_locale_parent_id_unique" ON "homepage_blocks_ylw_deck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_tags_order_idx" ON "homepage_blocks_feat_crd_tags" USING btree ("_order");
  CREATE INDEX "homepage_blocks_feat_crd_tags_parent_id_idx" ON "homepage_blocks_feat_crd_tags" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_feat_crd_tags_locales_locale_parent_id_uniqu" ON "homepage_blocks_feat_crd_tags_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_order_idx" ON "homepage_blocks_feat_crd" USING btree ("_order");
  CREATE INDEX "homepage_blocks_feat_crd_parent_id_idx" ON "homepage_blocks_feat_crd" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_path_idx" ON "homepage_blocks_feat_crd" USING btree ("_path");
  CREATE INDEX "homepage_blocks_feat_crd_image_idx" ON "homepage_blocks_feat_crd" USING btree ("image_id");
  CREATE UNIQUE INDEX "homepage_blocks_feat_crd_locales_locale_parent_id_unique" ON "homepage_blocks_feat_crd_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_acc_feat_crds_order_idx" ON "homepage_blocks_feat_crd_acc_feat_crds" USING btree ("_order");
  CREATE INDEX "homepage_blocks_feat_crd_acc_feat_crds_parent_id_idx" ON "homepage_blocks_feat_crd_acc_feat_crds" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_acc_feat_crds_mascot_idx" ON "homepage_blocks_feat_crd_acc_feat_crds" USING btree ("mascot_id");
  CREATE UNIQUE INDEX "homepage_blocks_feat_crd_acc_feat_crds_locales_locale_parent" ON "homepage_blocks_feat_crd_acc_feat_crds_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_acc_order_idx" ON "homepage_blocks_feat_crd_acc" USING btree ("_order");
  CREATE INDEX "homepage_blocks_feat_crd_acc_parent_id_idx" ON "homepage_blocks_feat_crd_acc" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_feat_crd_acc_path_idx" ON "homepage_blocks_feat_crd_acc" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_feat_crd_acc_locales_locale_parent_id_unique" ON "homepage_blocks_feat_crd_acc_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_list_crd_dck_cards_tags_order_idx" ON "homepage_blocks_list_crd_dck_cards_tags" USING btree ("_order");
  CREATE INDEX "homepage_blocks_list_crd_dck_cards_tags_parent_id_idx" ON "homepage_blocks_list_crd_dck_cards_tags" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_list_crd_dck_cards_tags_locales_locale_paren" ON "homepage_blocks_list_crd_dck_cards_tags_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_list_crd_dck_cards_order_idx" ON "homepage_blocks_list_crd_dck_cards" USING btree ("_order");
  CREATE INDEX "homepage_blocks_list_crd_dck_cards_parent_id_idx" ON "homepage_blocks_list_crd_dck_cards" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_list_crd_dck_cards_image_idx" ON "homepage_blocks_list_crd_dck_cards" USING btree ("image_id");
  CREATE UNIQUE INDEX "homepage_blocks_list_crd_dck_cards_locales_locale_parent_id_" ON "homepage_blocks_list_crd_dck_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_list_crd_dck_buttons_order_idx" ON "homepage_blocks_list_crd_dck_buttons" USING btree ("_order");
  CREATE INDEX "homepage_blocks_list_crd_dck_buttons_parent_id_idx" ON "homepage_blocks_list_crd_dck_buttons" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_list_crd_dck_buttons_locales_locale_parent_i" ON "homepage_blocks_list_crd_dck_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_list_crd_dck_order_idx" ON "homepage_blocks_list_crd_dck" USING btree ("_order");
  CREATE INDEX "homepage_blocks_list_crd_dck_parent_id_idx" ON "homepage_blocks_list_crd_dck" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_list_crd_dck_path_idx" ON "homepage_blocks_list_crd_dck" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_list_crd_dck_locales_locale_parent_id_unique" ON "homepage_blocks_list_crd_dck_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_faq_blk_faqs_order_idx" ON "homepage_blocks_faq_blk_faqs" USING btree ("_order");
  CREATE INDEX "homepage_blocks_faq_blk_faqs_parent_id_idx" ON "homepage_blocks_faq_blk_faqs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_faq_blk_faqs_locales_locale_parent_id_unique" ON "homepage_blocks_faq_blk_faqs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_faq_blk_order_idx" ON "homepage_blocks_faq_blk" USING btree ("_order");
  CREATE INDEX "homepage_blocks_faq_blk_parent_id_idx" ON "homepage_blocks_faq_blk" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_faq_blk_path_idx" ON "homepage_blocks_faq_blk" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_faq_blk_locales_locale_parent_id_unique" ON "homepage_blocks_faq_blk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_pink_puffy_top_row_order_idx" ON "homepage_blocks_pink_puffy_top_row" USING btree ("_order");
  CREATE INDEX "homepage_blocks_pink_puffy_top_row_parent_id_idx" ON "homepage_blocks_pink_puffy_top_row" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_pink_puffy_top_row_locales_locale_parent_id_" ON "homepage_blocks_pink_puffy_top_row_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_pink_puffy_bot_row_order_idx" ON "homepage_blocks_pink_puffy_bot_row" USING btree ("_order");
  CREATE INDEX "homepage_blocks_pink_puffy_bot_row_parent_id_idx" ON "homepage_blocks_pink_puffy_bot_row" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_pink_puffy_bot_row_locales_locale_parent_id_" ON "homepage_blocks_pink_puffy_bot_row_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_pink_puffy_links_order_idx" ON "homepage_blocks_pink_puffy_links" USING btree ("_order");
  CREATE INDEX "homepage_blocks_pink_puffy_links_parent_id_idx" ON "homepage_blocks_pink_puffy_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_pink_puffy_links_locales_locale_parent_id_un" ON "homepage_blocks_pink_puffy_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_pink_puffy_order_idx" ON "homepage_blocks_pink_puffy" USING btree ("_order");
  CREATE INDEX "homepage_blocks_pink_puffy_parent_id_idx" ON "homepage_blocks_pink_puffy" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_pink_puffy_path_idx" ON "homepage_blocks_pink_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_pink_puffy_locales_locale_parent_id_unique" ON "homepage_blocks_pink_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_beige_puffy_items_order_idx" ON "homepage_blocks_beige_puffy_items" USING btree ("_order");
  CREATE INDEX "homepage_blocks_beige_puffy_items_parent_id_idx" ON "homepage_blocks_beige_puffy_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_beige_puffy_items_locales_locale_parent_id_u" ON "homepage_blocks_beige_puffy_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_beige_puffy_order_idx" ON "homepage_blocks_beige_puffy" USING btree ("_order");
  CREATE INDEX "homepage_blocks_beige_puffy_parent_id_idx" ON "homepage_blocks_beige_puffy" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_beige_puffy_path_idx" ON "homepage_blocks_beige_puffy" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_beige_puffy_locales_locale_parent_id_unique" ON "homepage_blocks_beige_puffy_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_funding_map_items_subitems_order_idx" ON "homepage_blocks_funding_map_items_subitems" USING btree ("_order");
  CREATE INDEX "homepage_blocks_funding_map_items_subitems_parent_id_idx" ON "homepage_blocks_funding_map_items_subitems" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "homepage_blocks_funding_map_items_subitems_locales_locale_pa" ON "homepage_blocks_funding_map_items_subitems_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_funding_map_items_order_idx" ON "homepage_blocks_funding_map_items" USING btree ("_order");
  CREATE INDEX "homepage_blocks_funding_map_items_parent_id_idx" ON "homepage_blocks_funding_map_items" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_funding_map_order_idx" ON "homepage_blocks_funding_map" USING btree ("_order");
  CREATE INDEX "homepage_blocks_funding_map_parent_id_idx" ON "homepage_blocks_funding_map" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_funding_map_path_idx" ON "homepage_blocks_funding_map" USING btree ("_path");
  CREATE UNIQUE INDEX "homepage_blocks_funding_map_locales_locale_parent_id_unique" ON "homepage_blocks_funding_map_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "homepage_blocks_resource_feat_card_order_idx" ON "homepage_blocks_resource_feat_card" USING btree ("_order");
  CREATE INDEX "homepage_blocks_resource_feat_card_parent_id_idx" ON "homepage_blocks_resource_feat_card" USING btree ("_parent_id");
  CREATE INDEX "homepage_blocks_resource_feat_card_path_idx" ON "homepage_blocks_resource_feat_card" USING btree ("_path");
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // no-op
}
