const regionLabels: Record<string, Record<string, string>> = {
  'uaf-asia-pacific': {
    en: 'Asia & Pacific',
    ar: 'آسيا والمحيط الهادئ',
    bi: 'Asia & Pasifik',
    'bn-IN': 'এশিয়া ও প্রশান্ত',
    br: 'အာရှနှင့်ပစိဖိတ်',
    ch: '亚洲和太平洋',
    hi: 'एशिया और प्रशांत',
    km: 'អាស៊ី និងប៉ាស៊ីហ្វិក',
    ms: 'Asia & Pasifik',
    ne: 'एशिया र प्रशांत',
    pcm: 'Asia na Pasifik',
    'prs-Arab': 'آسیا و اقیانوسیه',
    'ps-Arab': 'آسیا او الکاهل',
    si: 'ආසියාව සහ පසිෆික්',
    ta: 'ஆசியா மற்றும் பசிபிக்',
    th: 'เอเชียและแปซิฟิก',
    tl: 'Asya at Pasipiko',
    ur: 'ایشیا اور بحر الکاہل',
    vi: 'Châu Á và Thái Bình Dương',
  },
  afghan: {
    en: 'Afghanistan',
    ar: 'أفغانستان',
    bi: 'Afghanistan',
    'bn-IN': 'আফগানিস্তান',
    br: 'အာဖဂန်နစ္စတန်',
    ch: '阿富汗',
    hi: 'अफ़ग़ानिस्तान',
    km: 'អាហ្វហ្គានីស្ថាន',
    ms: 'Afghanistan',
    ne: 'अफगानिस्तान',
    pcm: 'Afganistan',
    'prs-Arab': 'افغانستان',
    'ps-Arab': 'افغانستان',
    si: 'අෆ්ගනිස්ථානය',
    ta: 'அஃப்கானிஸ்தான்',
    th: 'อัฟกานิสถาน',
    tl: 'Afghanistan',
    ur: 'افغانستان',
    vi: 'Afghanistan',
  },
  aus: {
    en: 'Australia',
    ar: 'أستراليا',
    bi: 'Australia',
    'bn-IN': 'অস্ট্রেলিয়া',
    br: 'ဩစတြေးလိယာ',
    ch: '澳大利亚',
    hi: 'ऑस्ट्रेलिया',
    km: 'អូស្ត្រាលី',
    ms: 'Australia',
    ne: 'अस्ट्रेलिया',
    pcm: 'Ostrelia',
    'prs-Arab': 'استرالیا',
    'ps-Arab': 'آسترالیا',
    si: 'ඔස්ට්‍රේලියා',
    ta: 'ஆஸ்திரேலியா',
    th: 'ออสเตรเลีย',
    tl: 'Australia',
    ur: 'آسٹریلیا',
    vi: 'Australia',
  },
  bangla: {
    en: 'Bangladesh',
    ar: 'بنغلاديش',
    bi: 'Bangladesh',
    'bn-IN': 'বাংলাদেশ',
    br: 'ဘင်္ဂလာဒေရှ်',
    ch: '孟加拉国',
    hi: 'बांग्लादेश',
    km: 'បង់គ្លាដែស',
    ms: 'Bangladesh',
    ne: 'बंगलादेश',
    pcm: 'Banglades',
    'prs-Arab': 'بنگلادیش',
    'ps-Arab': 'بنگلهدیش',
    si: 'බංගළදේශය',
    ta: 'பங்களாதேசம்',
    th: 'บังคลาเทศ',
    tl: 'Bangladesh',
    ur: 'بنگلادیش',
    vi: 'Bangladesh',
  },
  cambodia: {
    en: 'Cambodia',
    ar: 'كمبوديا',
    bi: 'Kamboja',
    'bn-IN': 'কম্বোডিয়া',
    br: 'ကမ္ဘောဒီယာ',
    ch: '柬埔寨',
    hi: 'कम्बोडिया',
    km: 'កម្ពុជា',
    ms: 'Kemboja',
    ne: 'कम्बोडिया',
    pcm: 'Kambodiya',
    'prs-Arab': 'کامبوج',
    'ps-Arab': 'کمبوډیا',
    si: 'කොඹෝඩියා',
    ta: 'கம்போடியா',
    th: 'กัมพูชา',
    tl: 'Cambodia',
    ur: 'کمبوڈیا',
    vi: 'Campuchia',
  },
  china: {
    en: 'China',
    ar: 'الصين',
    bi: 'Tiongkok',
    'bn-IN': 'চীন',
    br: 'တရုတ်',
    ch: '中国',
    hi: 'चीन',
    km: 'ចិន',
    ms: 'China',
    ne: 'चीन',
    pcm: 'Saina',
    'prs-Arab': 'چین',
    'ps-Arab': 'چین',
    si: 'චීනය',
    ta: 'சீனம்',
    th: 'จีน',
    tl: 'Tsina',
    ur: 'چین',
    vi: 'Trung Quốc',
  },
  india: {
    en: 'India',
    ar: 'الهند',
    bi: 'India',
    'bn-IN': 'ভারত',
    br: 'အိန္ဒိယ',
    ch: '印度',
    hi: 'भारत',
    km: 'ប្រទេសឥណ្ឌា',
    ms: 'India',
    ne: 'भारत',
    pcm: 'India',
    'prs-Arab': 'هند',
    'ps-Arab': 'هندوستان',
    si: 'ඉන්දියා',
    ta: 'இந்தியா',
    th: 'อินเดีย',
    tl: 'India',
    ur: 'بھارت',
    vi: 'Ấn Độ',
  },
  indonesia: {
    en: 'Indonesia',
    ar: 'إندونيسيا',
    bi: 'Indonesia',
    'bn-IN': 'ইন্দোনেশিয়া',
    br: 'အင်ဒိုနီးရှ်',
    ch: '印度尼西亚',
    hi: 'इंडोनेशिया',
    km: 'ឥណ្ឌូណេស៊ី',
    ms: 'Indonesia',
    ne: 'इन्डोनेशिया',
    pcm: 'Indonesia',
    'prs-Arab': 'اندونیزیا',
    'ps-Arab': 'اندونیزیا',
    si: 'ඉන්දුනීසියා',
    ta: 'இந்தோனேசியா',
    th: 'อินโดนีเซีย',
    tl: 'Indonesia',
    ur: 'انڈونیشیا',
    vi: 'Indonesia',
  },
  korea: {
    en: 'Korea',
    ar: 'كوريا',
    bi: 'Korea',
    'bn-IN': 'কোরিয়া',
    br: 'ကိုရီးယား',
    ch: '韩国',
    hi: 'कोरिया',
    km: 'កូរ៉ីយ៉ា',
    ms: 'Korea',
    ne: 'कोरिया',
    pcm: 'Koria',
    'prs-Arab': 'کوریا',
    'ps-Arab': 'کوریا',
    si: 'කොරියා',
    ta: 'கொரியா',
    th: 'เกาหลี',
    tl: 'Korea',
    ur: 'کوریا',
    vi: 'Hàn Quốc',
  },
  laos: {
    en: 'Laos',
    ar: 'لاوس',
    bi: 'Laos',
    'bn-IN': 'লাওস',
    br: 'လာအို',
    ch: '老挝',
    hi: 'लाओस',
    km: 'លាវ',
    ms: 'Laos',
    ne: 'लाओस',
    pcm: 'Laos',
    'prs-Arab': 'لائوس',
    'ps-Arab': 'لاوس',
    si: 'ලාඕස්',
    ta: 'லாவோஸ்',
    th: 'ลาว',
    tl: 'Laos',
    ur: 'لاؤس',
    vi: 'Lào',
  },
  malaysia: {
    en: 'Malaysia',
    ar: 'ماليزيا',
    bi: 'Malaysia',
    'bn-IN': 'মালয়েশিয়া',
    br: 'မလေးရှား',
    ch: '马来西亚',
    hi: 'मलेशिया',
    km: 'ម៉ាឡេស៊ី',
    ms: 'Malaysia',
    ne: 'मलेशिया',
    pcm: 'Malesia',
    'prs-Arab': 'مالیزیا',
    'ps-Arab': 'مالیزیا',
    si: 'මලේසියාව',
    ta: 'மலேசியா',
    th: 'มาเลเซีย',
    tl: 'Malaysia',
    ur: 'ملائیشیا',
    vi: 'Malaysia',
  },
  mongolia: {
    en: 'Mongolia',
    ar: 'منغوليا',
    bi: 'Mongolia',
    'bn-IN': 'মঙ্গোলিয়া',
    br: 'မွန်ဂိုလီးယား',
    ch: '蒙古',
    hi: 'मंगोलिया',
    km: 'ម៉ុងហ្គោលី',
    ms: 'Mongolia',
    ne: 'मंगोलिया',
    pcm: 'Mongolia',
    'prs-Arab': 'مغولستان',
    'ps-Arab': 'مغولستان',
    si: 'මොන්ගෝලියාව',
    ta: 'மங்கோலியா',
    th: 'มองโกเลีย',
    tl: 'Mongolia',
    ur: 'منگولیا',
    vi: 'Mông Cổ',
  },
  myanmar: {
    en: 'Myanmar',
    ar: 'ميانمار',
    bi: 'Myanmar',
    'bn-IN': 'মিয়ানমার',
    br: 'မြန်မာ',
    ch: '缅甸',
    hi: 'म्यांमार',
    km: 'មីយ៉ាន់ម៉ា',
    ms: 'Myanmar',
    ne: 'म्यानमार',
    pcm: 'Myanma',
    'prs-Arab': 'میانمار',
    'ps-Arab': 'میانمار',
    si: 'මියන්මාරය',
    ta: 'மியான்மார்',
    th: 'เมียนมาร์',
    tl: 'Myanmar',
    ur: 'میانمار',
    vi: 'Myanmar',
  },
  nepal: {
    en: 'Nepal',
    ar: 'نيبال',
    bi: 'Nepal',
    'bn-IN': 'নেপাল',
    br: 'နီပေါ',
    ch: '尼泊尔',
    hi: 'नेपाल',
    km: 'នេប៉ាល់',
    ms: 'Nepal',
    ne: 'नेपाल',
    pcm: 'Nepal',
    'prs-Arab': 'نیپال',
    'ps-Arab': 'نیپال',
    si: 'නේපාලය',
    ta: 'நேபாளம்',
    th: 'เนปาล',
    tl: 'Nepal',
    ur: 'نیپال',
    vi: 'Nepal',
  },
  pak: {
    en: 'Pakistan',
    ar: 'باكستان',
    bi: 'Pakistan',
    'bn-IN': 'পাকিস্তান',
    br: 'ပါကစ္စတန်',
    ch: '巴基斯坦',
    hi: 'पाकिस्तान',
    km: 'ប៉ាគីស្ថាន',
    ms: 'Pakistan',
    ne: 'पाकिस्तान',
    pcm: 'Pakistan',
    'prs-Arab': 'پاکستان',
    'ps-Arab': 'پاکستان',
    si: 'පකිස්ථානය',
    ta: 'பாகிஸ்தான்',
    th: 'ปากีสถาน',
    tl: 'Pakistan',
    ur: 'پاکستان',
    vi: 'Pakistan',
  },
  papua: {
    en: 'Papua New Guinea',
    ar: 'بابوا غينيا الجديدة',
    bi: 'Papua Nugini',
    'bn-IN': 'পাপুয়া নিউ গিনি',
    br: 'ပပူဝါနယူးဂီနီ',
    ch: '巴布亚新几内亚',
    hi: 'पापुआ न्यू गिनी',
    km: 'ប៉ាពួញូហ្គីនេ',
    ms: 'Papua New Guinea',
    ne: 'पापुआ न्यू गिनी',
    pcm: 'Papua Niugini',
    'prs-Arab': 'پاپوا غینۀ نو',
    'ps-Arab': 'پاپوا نیوه ګیني',
    si: 'පපුවා නිව් ගිනිය',
    ta: 'பாபுவா நியூ கினி',
    th: 'ปาปัวนิวกินี',
    tl: 'Papua New Guinea',
    ur: 'پاپوا نیو گنی',
    vi: 'Papua New Guinea',
  },
  philippines: {
    en: 'Philippines',
    ar: 'الفلبين',
    bi: 'Filipina',
    'bn-IN': 'ফিলিপাইন',
    br: 'ဖိလစ်ပိုင်',
    ch: '菲律宾',
    hi: 'फिलीपींस',
    km: 'ហ្វីលីពីន',
    ms: 'Filipina',
    ne: 'फिलिपींस',
    pcm: 'Filipin',
    'prs-Arab': 'فلیپین',
    'ps-Arab': 'فلپین',
    si: 'ෆිලිපීනය',
    ta: 'பிலிப்பைன்ஸ்',
    th: 'ฟิลิปปินส์',
    tl: 'Pilipinas',
    ur: 'فلپائن',
    vi: 'Philippines',
  },
  srilanka: {
    en: 'Sri Lanka',
    ar: 'سريلانكا',
    bi: 'Sri Lanka',
    'bn-IN': 'শ্রীলঙ্কা',
    br: 'သီရိလင်္ကာ',
    ch: '斯里兰卡',
    hi: 'श्रीलंका',
    km: 'ស្រីលង្កា',
    ms: 'Sri Lanka',
    ne: 'श्रीलंका',
    pcm: 'Sri Lanka',
    'prs-Arab': 'سریلانکا',
    'ps-Arab': 'سریلانکا',
    si: 'ශ්‍රී ලංකාව',
    ta: 'ஸ்ரீலங்கா',
    th: 'ศรีลังกา',
    tl: 'Sri Lanka',
    ur: 'سری لنکا',
    vi: 'Sri Lanka',
  },
  thailand: {
    en: 'Thailand',
    ar: 'تايلاند',
    bi: 'Thailand',
    'bn-IN': 'থাইল্যান্ড',
    br: 'ထိုင်း',
    ch: '泰国',
    hi: 'थाईलैंड',
    km: 'ថៃ',
    ms: 'Thailand',
    ne: 'थाइलैंड',
    pcm: 'Tailan',
    'prs-Arab': 'تایلند',
    'ps-Arab': 'تایلنډ',
    si: 'තායිලන්තය',
    ta: 'தாய்லாந்து',
    th: 'ประเทศไทย',
    tl: 'Thailand',
    ur: 'تھائی لینڈ',
    vi: 'Thailand',
  },
  vietnam: {
    en: 'Vietnam',
    ar: 'فيتنام',
    bi: 'Vietnam',
    'bn-IN': 'ভিয়েতনাম',
    br: 'ဗီယက်နမ်',
    ch: '越南',
    hi: 'वियतनाम',
    km: 'វៀតណាម',
    ms: 'Vietnam',
    ne: 'वियतनाम',
    pcm: 'Vietnam',
    'prs-Arab': 'ویتنام',
    'ps-Arab': 'ویتنام',
    si: 'වියට්නාමය',
    ta: 'வியட்நாம்',
    th: 'เวียดนาม',
    tl: 'Vietnam',
    ur: 'ویتنام',
    vi: 'Việt Nam',
  },
}

export function getLocalizedRegionLabel(value: string, locale: string): string {
  const labels = regionLabels[value]
  if (!labels) return value
  return labels[locale] ?? labels['en'] ?? value
}
